<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Edit User
       </h1>
     </section>
     <!-- Main content -->
    <section class="content">
     <?php if($this->errors){ echo $this->errors;}?>
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
             <!-- form start -->
            <form role="form" action="" method="post" id="user_form" name="user_form">
              <div class="box-body">
                <div class="row form-group">
				<div class="col-sm-4">
				 <label for="exampleInputEmail1">Name<span class="error">*</span></label>
                  <input type="text" name="name" id="name" class="form-control" value="<?php echo $this->userIntro['name'];?>" />
				  <div id="nameError" class="error"></div>
                 </div>
				 <div class="col-sm-4">
				 <label for="exampleInputPassword1">Username<span class="error">*</span></label>
                  <input type="text" name="username" readonly="readonly" id="username" class="form-control" value="<?php echo $this->userIntro['username'];?>" />
				  
                 </div>
				 <div class="col-sm-4">
				 <label for="exampleInputPassword1">Password<span class="error">*</span></label>
                   <input type="password" name="password" id="password" class="form-control" value="<?php echo $this->userIntro['password'];?>" />
				    <input type="hidden" name="old_password"value="<?php echo $this->userIntro['password'];?>" /> 
                 </div>
				 </div>
				 
				 <div class="row form-group">				
				 <div class="col-sm-3">
				 <label for="exampleInputPassword1">Confirm Password<span class="error">*</span></label>
                   <input type="password" name="cpassword" id="cpassword" class="form-control" value="<?php echo $this->userIntro['password'];?>" />
                 </div>
				 <div class="col-sm-3">
				 <label for="exampleInputPassword1">Email ID<span class="error">*</span></label>
                  <input type="text" name="email_id" id="email_id" value="<?php echo $this->userIntro['email_id'];?>" class="form-control" />
				  <div id="email_idError" class="error"></div>
                 </div>
				 <div class="col-sm-3">
				 <label for="exampleInputPassword1">Mobile No.<span class="error">*</span></label>
                  <input type="text" name="mobile_no" id="mobile_no" value="<?php echo $this->userIntro['mobile_no'];?>" class="form-control" />
				  <div id="mobile_noError" class="error"></div>
                 </div>
				 <div class="col-sm-3">
                  <label for="exampleInputPassword1">User Type<span class="error">*</span></label>
                  <select name="user_type" id="user_type" class="form-control" onchange="changeUserType()">
				  <option value="">Select User Type</option>
				  <option value="sub-admin" <?=($this->userIntro['user_type']=="sub-admin")?"selected":""?>>Sub Admin</option>
				  <option value="user" <?=($this->userIntro['user_type']=="user")?"selected":""?>>User</option>
				  <option value="Data Manager" <?=($this->userIntro['user_type']=="Data Manager")?"selected":""?>>Data Manager</option>
				  <option value="Consultant" <?=($this->userIntro['user_type']=="Consultant")?"selected":""?>>Consultant</option>
				  </select>
				  <div id="user_typeError" class="error"></div>
                  </div>
				  
				 
				 </div>
                 
               
				 
				  <div class="row form-group">
				  
				 <div class="col-sm-4">
				 <div class="form-group">
                  <label for="exampleInputPassword1">Select Team</label>
                  <select name="team_id[]" id="team_id" multiple class="form-control select2">
				  <option value="">Select Team</option>
					 <?php
					foreach($this->teamsArr as $team)
					{ 
					$array= explode(",",$this->userIntro['team_id']);
					if(in_array($team['id'],explode(",",$this->userIntro['team_id'])))
					{
					 $select='selected';
					}
					else
					{
					$select='';	
					}
					?>
					<option value="<?php echo $team['id'];?>" <?=$select?>><?php echo $team['team_name'];?></option> 	
					<?php }
					?>                               
					</select>
					<div id="team_idError" class="error"></div>
                  </div>
				 </div>
				 
				
                 <div class="col-sm-4">
				 <div class="form-group">
                  <label for="exampleInputPassword1">Category</label>
				  <div class="row">
                  <div class="col-sm-6">
				  <input type="radio" name="category" id="category1" class="flat-red" <?=($this->userIntro['category']=="PhD")?"checked":""?> value="PhD" >
				  <label for="category1">PhD</label>
				  </div>
				  <div class="col-sm-6">
				  <input type="radio" name="category" id="category2" class="flat-red" <?=($this->userIntro['category']=="Sales")?"checked":""?> value="Sales" >
				  <label for="category2">Sales</label>
				  </div>
				  </div>
				  <div id="categoryError" class="error"></div>
                   </div>
				 </div>
				 

				<div class="col-sm-12" id="profileDiv">
				   
				  
				  
				   <div class="form-group">
				      <table class="table table-bordered table-responsive">
        
        <?php if(count($this->userProfile) > 0){
			 
			foreach($this->userProfile as $profile)
			{
			?>
         <tr id="oldprofile<?=$profile['id']?>">
          <td>
		  <input type="hidden" name="profile_id[]" value="<?=$profile['id']?>">
           <label for="exampleInputPassword1">Profile Name<span class="error">*</span></label>
           <input type="text" name="old_profile_name[]" required="required" id="old_profile_name<?=$profile['id'];?>" class="form-control" value="<?php echo $profile['profile_name'];?>" placeholder="Profile Name"/>
          </td>
        <td>
        <label for="exampleInputPassword1">Website<span class="error">*</span></label>
        <select name="old_website[]" id="old_website<?=$profile['id']?>" class="form-control" required="required">
		<option value="">Select Website</option>
		<?php
		foreach($this->WebsiteData as $website)
		{ 
		?>
        <option value="<?=$website['id']?>" <?=($profile['website']==$website['id'])?"selected":""?>><?=$website['website']?></option>
		<?php }?>
        </select>
        </td>
		<td>
        <label for="exampleInputPassword1">Website Email ID<span class="error">*</span></label>
		 <input type="text" name="old_website_email[]" required="required" id="old_website_email<?=$profile['id']?>" class="form-control" value="<?=$profile['website_email']?>" placeholder="Website Email"/>
         
        </td>
		<td style="width:400px;">
        <label for="exampleInputPassword1">Signature<span class="error">*</span></label>
		 <textarea style="height:70px;" name="old_signature[]" required="required" id="old_signature<?=$profile['id']?>" class="form-control textarea" placeholder="Signature"><?=$profile['signature']?></textarea>
         
        </td>
		
           <td style="padding:25px 0 0 10px; font-weight: 700; font-size:20px;">
            <a style="cursor:pointer;" onclick="deleteUserProfile(<?=$profile['id']?>);"> - </a>
           </td> 
         </tr>
          <?php } } ?>
		  
		  
         <tr>
          <td>
           <label for="exampleInputPassword1">Profile Name<span class="error">*</span></label>
           <input type="text" name="profile_name[]"  id="profile_name1" class="form-control" value="" placeholder="Profile Name"/>
          </td>
        <td>
        <label for="exampleInputPassword1">Website<span class="error">*</span></label>
        <select name="website[]" id="website1" class="form-control">
		<option value="">Select Website</option>
		<?php
		foreach($this->WebsiteData as $website)
		{ 
		?>
        <option value="<?=$website['id']?>"><?=$website['website']?></option>
		<?php }?>
        </select>
        </td>
		<td>
        <label for="exampleInputPassword1">Website Email ID<span class="error">*</span></label>
		 <input type="text" name="website_email[]" id="website_email1" class="form-control" value="" placeholder="Website Email"/>
         
        </td>
		<td style="width:400px;">
        <label for="exampleInputPassword1">Signature<span class="error">*</span></label>
		 <textarea style="height:70px;" name="signature[]" id="signature" class="form-control textarea" value="" placeholder="Signature"></textarea>
         
        </td>
           <!-- <td style="padding:25px 0 0 10px; font-weight: 700; font-size:20px;">
          <a style="cursor:pointer;" onclick="addMore();"> + </a>
           </td>-->
         </tr>
         <input type="hidden" id="addcounter" value="1">
          
        </table>
        <table id="add_followup" class="table table-bordered table-responsive"></table>

       
				   </div>
				  
				 </div>
				  
				  
				 
				 </div>
				 

				 <div class="row form-group" style="display:none;">
				 <div class="col-sm-4">
				 <input type="checkbox" name="whatsaap_notification" id="whatsaap_notification" class="flat-red" <?php if($this->userIntro['whatsaap_notification']=='on'){ echo "checked";}?> >
				 <label for="exampleInputPassword1">WhatsApp Notification</label>
                 </div>
				 
				 <div class="col-sm-4">
				 <input type="checkbox" name="sms_notify" id="sms_notify" class="flat-red" <?php if($this->userIntro['sms_notify']=='on'){ echo "checked";}?> >
				 <label for="exampleInputPassword1">SMS/Email Notification</label>
                 </div>
				 <div class="col-sm-4">
				 <input type="checkbox" name="download_option" id="download_option" class="flat-red" <?php if($this->userIntro['download_option']=='on'){ echo "checked";}?>>
				 <label for="exampleInputPassword1">Download Option</label>
                 </div>
				 </div>
				 
                 
                  
                <div class="row form-group">
				<div class="col-sm-12">
				<div class="box-footer">
                 <input type="submit" name="submitBtn" id="submitBtn" class="btn btn-primary" value="Submit" onclick="return SubmitUser()" />
				 &nbsp;&nbsp;&nbsp;
				 <input type="button" class="btn bg-maroon" onclick="parent.location='<?=SITEURL?>manageuser'" value="Cancel">
              </div>
				</div>
				</div>
		
              
            </form>
          </div>
          <!-- /.box -->

       

        </div>
        <!--/.col (left) -->
        <!-- right column -->
         
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  
 
  
 
 <script type="text/javascript">
function SubmitUser()
{ 
 var error="";
if(document.user_form.name.value=="")
{
$("#nameError").html("Please enter name");
error=1;	
}	
if(document.user_form.email_id.value=="")
{
$("#email_idError").html("Please enter email id");
error=1;	
}
if(document.user_form.mobile_no.value=="")
{
$("#mobile_noError").html("Please enter mobile no.");
error=1;	
}
if(document.user_form.user_type.value=="")
{
$("#user_typeError").html("Please select user type");
error=1;	
}
if(document.user_form.team_id.value=="")
{
$("#team_idError").html("Please select team");
error=1;	
} 
 if(document.user_form.category1.checked==false && document.user_form.category2.checked==false)
{
$("#categoryError").html("Please select category");
error=1;	
}
if(error==1)
{
return false;
}
else
{
	return true;
}

 }
 
 function addMore()
 {
var counter=$("#addcounter").val();
counter++;

 var html='<tr id="foloowupspace'+counter+'">';
	    html+='<td><label for="exampleInputPassword1">Profile Name<span class="error">*</span></label><input type="text" name="profile_name[]" required="required" id="profile_name'+counter+'" class="form-control" value="" placeholder="Profile Name" /></td>';
		html+='<td><label for="exampleInputPassword1">Website<span class="error">*</span></label><select name="website[]" id="website'+counter+'" class="form-control"><option value="">Select Website</option>';
		<?php
		foreach($this->WebsiteData as $website)
		{ 
		?>
		html+='<option value="<?=$website['id']?>"><?=$website['website']?></option>';
		<?php } ?>
		html+='</select></td>';
		
		html+='<td><label for="exampleInputPassword1">Website Email ID<span class="error">*</span></label><input type="text" name="website_email[]" required="required" id="website_email'+counter+'" class="form-control" value="" placeholder="Website Email" /></td>';
		
		html+='<td><label for="exampleInputPassword1">Signature<span class="error">*</span></label><textarea name="signature[]" required="required" id="signature'+counter+'" class="form-control" placeholder="Signature" ></textarea></td>';
		
		html+='<td style="padding:25px 0 0 10px; font-weight: 700; font-size:20px;"><a style="cursor:pointer;" onclick="removeFolowup('+counter+');"> - </a></td>';
 		html+='</tr>';
		
		
		if(counter < 7)
		{
	$("#addcounter").val(counter);
	 
	$( "#add_followup" ).append(html);	 
		}
   }

 function removeFolowup(counterid)
{
	
$("#foloowupspace"+counterid).remove();
var counter=$("#addcounter").val();
counter--;
$("#addcounter").val(counter);
}
function deleteUserProfile(pid)
{
  if (confirm("Are you sure you want to delete?"))
  {
	$.ajax({
    type : 'POST',
    url : '<?php echo SITEURL?>manageuser/index/deleteuserprofile',
    data :"profile_id="+pid,
	cache:false,
	beforeSend: function()
	{
 	},

	success: function(response)
	{
	 $("#oldprofile"+response).remove();
	}
  });  
  }	

	
}


function changeUserType()
{  
if($("#user_type").val()=='user')
{
$("#profileDiv").show();	
}
else
{
$("#profileDiv").hide();
}
}
changeUserType();
$(function () {
	$('.textarea').wysihtml5({});
 });
 
</script>