<div class="col-md-12">
           <div class="box box-primary direct-chat direct-chat-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Show Conversation To <?php echo $this->userData['name'];?></h3>
              </div>
             <div class="box-body">
               <div class="direct-chat-messages" id="ShowMessage">
                <?php echo $this->messageList;?>
                </div>
             </div>
             <div class="box-footer">
              <form action="#" method="post">
                <div class="input-group">
                 <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->userData['id'];?>">
        <input type="hidden" name="sender_id" id="sender_id" value="<?php echo $this->userInfo->id;?>">
                  <input type="text" name="message" id="message" placeholder="Type Message ..." class="form-control">
                      <span class="input-group-btn">
                        <button type="button" class="btn btn-primary btn-flat" onclick="return submitMessage()">Send</button>
                      </span>
                </div>
              </form>
            </div>
           </div>
         </div>

       
      
<script type="text/javascript">
function submitMessage()
{
var user_id=$("#user_id").val();
var sender_id=$("#sender_id").val();	
var message=$("#message").val();

if(message=="")
{
$("#message").css("border-color","#C00");
return false;	
}
else
{
$.ajax({
    type : 'POST',
    url : "<?php echo SITEURL?>manageuser/index/savemessage/user_id/"+user_id+"/sender_id/"+sender_id+"/message/"+message,
	cache:false,
	beforeSend: function()
	{
	$('#Regloader').show();
	},
	success: function(response)
	{
	setTimeout(function() { $("#Regloader").fadeOut(500);
	$("#ShowMessage").html(response);
	$("#message").css("border-color","");
		$("#message").val("");
 	 }, 1000);
	}
	
});

}




/*$.post("<?php echo SITEURL?>manageuser/index/savemessage/user_id/"+user_id+"/sender_id/"+sender_id+"/message/"+message, function( data ) {
		$("#ShowMessage").html(data);
		$("#message").val("");
    });*/	
}
</script>