<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1></h1>
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h2>
        Add Tags
       </h2>
          <!-- general form elements -->
          <div class="box box-primary">
             <!-- form start -->
            <form role="form" action="" method="post" id="user_form" name="user_form">
              <div class="box-body pt-3">
                <div class="row form-group">
				
				<div class="col-sm-12">
                  <label for="exampleInputEmail1">Tag Name<span class="error">*</span></label>
                  <input type="text" name="tag_name" id="tag_name" required="required" class="form-control" value="<?php echo $this->tagInfo['tag_name'];?>" />
                 </div>
				
				
				
				<?php if($this->userInfo->user_type=="admin"){?>
				<div class="col-sm-4">
                  <div class="form-group">
                  <label for="exampleInputPassword1">Category</label>
				  <div class="row">
                  <div class="col-sm-6">
				  <input type="radio" required name="category" id="category1" <?=($this->tagInfo['category']=='PhD')?"checked":""?> class="flat-red" value="PhD" >
				  <label for="category1">PhD</label>
				  </div>
				  <div class="col-sm-6">
				  <input type="radio" required name="category" id="category2" <?=($this->tagInfo['category']=='Sales')?"checked":""?> class="flat-red" value="Sales" >
				  <label for="category2">Sales</label>
				  </div>
				  </div>
				  <div id="categoryError" class="error"></div>
                   </div>
                 </div>
				<?php } else { ?>
					<input type="hidden" name="category" class="flat-red" value="<?=($this->tagInfo)?$this->tagInfo['category']:$this->userInfo->category?>" >
				<?php }?>
				
				
				
				<?php if($this->userInfo->user_type=="admin"){?>
				<div class="col-sm-4">
                  <div class="form-group">
                  <label for="exampleInputPassword1">Tags Type</label>
				  <div class="row">
                  <div class="col-sm-6">
				  <input type="radio" required name="tag_type" id="tag_type1" <?=($this->tagInfo['tag_type']=='Primary')?"checked":""?> class="flat-red" value="Primary" >
				  <label for="tag_type1">Primary Tags</label>
				  </div>
				  <div class="col-sm-6">
				  <input type="radio" required name="tag_type" id="tag_type2" <?=($this->tagInfo['tag_type']=='Secondary')?"checked":""?> class="flat-red" value="Secondary" >
				  <label for="tag_type2">Secondary Tags</label>
				  </div>
				  </div>
				  <div id="categoryError" class="error"></div>
                   </div>
                 </div>
				<?php } else { ?>
					<input type="hidden" name="tag_type" class="flat-red" value="Secondary" >
				<?php }?>
				
				
				 
				  </div>
				  
				  <div class="row form-group">
				<div class="col-sm-12">
				<div class="box-footer">
                <input type="submit" name="submitBtn" id="submitBtn" class="btn btn-primary" value="submit" />
				
				&nbsp;&nbsp;
				  <input type="button" class="btn bg-maroon" onClick="parent.location='<?=SITEURL?>tags'"  value="Cancel" />
              </div>
				</div>
				</div>
				  
                  </div>
              <!-- /.box-body -->
            </form>
          </div>
          <!-- /.box -->
          </div>
          <div class="col-md-4"></div>
        <!--/.col (left) -->
        <!-- right column -->
         <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <script src="<?=PUBLICURL?>bootstrap/js/jquery.js"></script>
<script src="<?=PUBLICURL?>bootstrap/js/jquery.validate.js"></script>
 <script type="text/javascript">
$(document).ready(function() {
     var Validator = jQuery('#user_form').validate({
         rules: {
 	        tag_name: "required",
 	        tag_type: "required",
          },
		  
 		messages: {
 			tag_name: " Please enter tag name",
 			tag_type: " Please check tag type",
             }
 
     });
  
 });
 
 
</script>