<?php
 $date = new Zend_Date();
?>
<style>
.dateFilterClass label {
    background: #e0e0e0;
}
</style>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1> Edit Query </h1>
       
    </section>
 
    <!-- Main content -->
    <section class="content">
    <?php if($this->errors){ echo $this->errors;}?>
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
             <!-- form start -->
            <form role="form" action="" method="post" id="query_form" name="query_form" enctype="multipart/form-data">
			<input type="hidden" name="entrytype" value="<?=$this->QueryInfo['entrytype']?>">
			<input type="hidden" name="date" id="date" value="<?php echo $this->QueryInfo['date'];?>"  class="form-control tcal" >
              <div class="box-body">
		 
			  
			  <div class="col-sm-4"  style="display:<?=($this->QueryInfo['entrytype']=='PhD')?'block':'none'?>">
                <div class="form-group">
                  <label for="exampleInputEmail1">Query Code<span class="error">*</span></label>
				  <select name="query_code" id="query_code" class="form-control">
				  <option value="">Select Query Code</option>
				  <option value="GH56671" <?=($this->QueryInfo['query_code']=='GH56671')?"selected":""?>>GH56671</option>
				  <option value="654QTYP" <?=($this->QueryInfo['query_code']=='654QTYP')?"selected":""?>>654QTYP</option>
				  <option value="C9-987-EE" <?=($this->QueryInfo['query_code']=='C9-987-EE')?"selected":""?>>C9-987-EE</option>
				  <option value="7651/09/7145" <?=($this->QueryInfo['query_code']=='7651/09/7145')?"selected":""?>>7651/09/7145</option>
				  <option value="15:98716" <?=($this->QueryInfo['query_code']=='15:98716')?"selected":""?>>15:98716</option>
			      <option value="E3W33BS" <?=($this->QueryInfo['query_code']=='E3W33BS')?"selected":""?>>E3W33BS</option>
				  <option value="AG6521" <?=($this->QueryInfo['query_code']=='AG6521')?"selected":""?>>AG6521</option>
				  <option value="F3485TK" <?=($this->QueryInfo['query_code']=='F3485TK')?"selected":""?>>F3485TK</option>
 				  </select>
                  <span id="query_codeError" class="error"></span>
                 </div>
                 </div>
				 <div class="col-sm-4">
				 <div class="form-group">
                  <label for="exampleInputEmail1">Client Name<span class="error">*</span></label>
                  <input type="text" name="name" id="name" class="form-control" value="<?php echo $this->QueryInfo['name'];?>" />
                  <span id="nameError" class="error"></span>
                 </div>
                 </div>
                 <div class="col-sm-4">
                 <div class="form-group">
                  <label for="exampleInputPassword1">Client Email ID<span class="error">*</span></label>
                  <input type="text" name="email_id" id="email_id" value="<?php echo $this->QueryInfo['email_id'];?>" class="form-control" />
                  <span id="email_idError" class="error"></span>
                  </div>
                  </div>
                  <div class="col-sm-4">
                   <div class="form-group">
                  <label for="exampleInputPassword1">Alternate Email ID</label>
                  <input type="text" name="alt_email_id" id="alt_email_id" value="<?php echo $this->QueryInfo['alt_email_id'];?>" class="form-control" />
                   </div>
                   </div>
                 <div class="col-sm-4">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Phone No.</label>
                 <input type="text" name="phone" id="phone" value="<?php echo $this->QueryInfo['phone'];?>" class="form-control" /> 
				 </div>
				 </div>
                 <div class="col-sm-4">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Alternate  Contact No.</label>
                 <input type="text" name="alt_contact_no" id="alt_contact_no" value="<?php echo $this->QueryInfo['alt_contact_no'];?>" class="form-control" /> 
                 </div>
                 </div>
                 
                 <div class="col-sm-4">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Location</label>
                <select name="location" id="location" class="form-control">
                 <option value="">Please Select</option>
                 <?php
                 foreach($this->CountryData as $Country)
				 { ?>
					<option value="<?php echo $Country['nicename'];?>" <?php if($this->QueryInfo['location']==$Country['nicename']){ ?> selected="selected" <?php }?>><?php echo $Country['nicename'];?></option> 
				<?php  }
				 ?>
                 </select>
                </div>
                </div>
				<div class="col-sm-4">
                 <div class="form-group">
                 <label for="exampleInputPassword1">City</label>
                 <input type="text" name="city" id="city" value="<?php echo $this->QueryInfo['city'];?>" class="form-control" />  
                   </div>
                   </div>
				   
				  <!-- <div class="col-sm-4" style="display:none;">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Complete Address</label>
                 <input type="text" name="complete_address" id="complete_address" value="<?php echo $this->QueryInfo['complete_address'];?>" class="form-control" />  
                   </div>
                   </div>-->
				   
                   <div class="col-sm-4"  style="display:<?=($this->QueryInfo['entrytype']=='PhD')?'none':'block'?>">
                   <div class="form-group">
				    <label for="exampleInputPassword1">Client Company</label>
				  <input type="text" name="company_name" id="company_name" value="<?php echo $this->QueryInfo['company_name'];?>" class="form-control" /> 
				   
				    <span id="company_nameError" class="error"></span>
                   </div>
                   </div>
                   <!-- <div class="col-sm-4" style="display:none;">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Designation</label>
                 <input type="text" name="designation" id="designation" value="<?php echo $this->QueryInfo['designation'];?>" class="form-control" />  
                 </div>
                 </div>-->
                <div class="col-sm-4" style="display:<?=($this->userInfo->user_type!='user')?'block':'none'?>">
                <div class="form-group">
                 <label for="exampleInputPassword1">Website</label>
                <select name="website" id="website" class="form-control" onchange="OtherFunction();">
                 <option value="">Please Select</option>
                 <?php
                 foreach($this->WebsiteData as $Website)
				 { ?>
					<option value="<?php echo $Website['id'];?>" <?php if($this->QueryInfo['website_id']==$Website['id']){ ?> selected="selected" <?php }?>><?php echo $Website['website'];?></option> 
				<?php  }
				 ?>
                 </select>
                 <span id="websiteError" class="error"></span>
                </div>
                </div>
                 <div class="col-sm-4" id="other_website_div" <?php if($this->QueryInfo['website_id']!=20){?>style="display:none;" <?php }?>>
                <div class="form-group">
                 <label for="exampleInputPassword1">Other Website</label>
                 <input type="text" name="other_website" id="other_website" value="<?php echo $this->QueryInfo['other_website'];?>" class="form-control" />
                 <span id="other_websiteError" class="error"></span>
                 </div>
                 </div>
                 
                  <div class="col-sm-4"  style="display:<?=($this->QueryInfo['entrytype']=='PhD')?'block':'none'?>">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Topic/Area of study</label>
                 <input type="text" name="area_of_study" id="area_of_study" value="<?php echo $this->QueryInfo['area_of_study'];?>" class="form-control" />    
                   </div>
                   </div>
                 
                <div class="col-sm-4">
                <div class="form-group">
                 <label for="exampleInputPassword1">Requirement</label>
                  <select name="requirement" id="requirement" class="form-control" onchange="otherRequirement()">
                 <option value="">Please Select</option>
				 <?php foreach($this->serviceData as $service)
				 { ?>
				  <option value="<?=$service['id']?>" <?php if($this->QueryInfo['requirement']==$service['id']){ ?> selected="selected" <?php }?>><?=$service['name']?></option>	 
				<?php  }?>
				   
				 
                 </select>
				 <span id="requirementError" class="error"></span>
                 </div>
                 </div>
                 
                 <div class="col-sm-4" id="other_requirement_div"  <?php if($this->QueryInfo['requirement']!=20){?>style="display:none;" <?php }?>>
				 <div class="form-group">
                 <label for="exampleInputPassword1">Other Requirement</label>
                 <input type="text" name="other_requirement" id="other_requirement" value="<?php echo $this->QueryInfo['other_requirement'];?>" class="form-control" />
				 <span id="other_requirementError" class="error"></span>
                  </div>
                  </div>
               
                
                
				  
				 <div class="col-sm-4" style="display:<?=($this->userInfo->user_type!='user')?'block':'none'?>">
				 <div class="form-group">
                  <label for="exampleInputPassword1">Select Team</label>
                  <select name="team_id" id="team_id" class="form-control" onchange="changeTeam()">
				  <option value="">Select Team</option>
					 <?php
					foreach($this->teamsArr as $team)
					{ 
					?>
					<option value="<?php echo $team['id'];?>" <?=($this->QueryInfo['team_id']==$team['id'])?"selected":""?>><?php echo $team['team_name'];?></option> 	
					<?php }
					?>                               
					</select>
					<span id="team_idError" class="error"></span>
                  </div>
				 </div>
				 <div class="col-sm-4" style="display:<?=($this->userInfo->user_type!='user')?'block':'none'?>">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Allocated To</label>
                <select name="allocated_to" id="allocated_to" class="form-control select2" data-placeholder="Select a User" onchange="changeAllocateUser()">
				                    <option value="">Select User</option>
							<?php
								foreach($this->ActiveUsers as $users)
								{ 
								if(in_array($users['id'],$this->queryUser))
								{
								$select="selected";	
								}
								else
								{
								$select="";		
								}
								?>
								<option value="<?php echo $users['id'];?>" <?php echo $select;?>><?php echo $users['username'];?></option> 	
							<?php } ?>                               
                </select>
                                    <span id="allocated_toError" class="error"></span>
                </div>
                </div>
				 <div class="col-sm-4">
				 <div class="form-group">
                  <label for="exampleInputPassword1">Select Profile</label>
                  <select name="profile_id" id="profile_id" class="form-control">
				  <option value="">Select Profile</option>
				  </select>
				  <span id="profile_idError" class="error"></span>
                  </div>
				 </div>
				 
				 <div class="col-sm-4">
				 <div class="form-group">
                  <label for="exampleInputPassword1">Select Tags</label>
                  <select name="tags[]" id="tags" multiple class="form-control select2">
				  <option value="">Select Tag</option>
					 <?php
					foreach($this->tagsArr as $tag)
					{ 
					$array= explode(",",$this->QueryInfo['tags']);
					if(in_array($tag['id'],$array))
					{
					 $select='selected';
					}
					else
					{
					$select='';	
					}
					?>
					<option value="<?=$tag['id']?>" <?=$select?>><?php echo $tag['tag_name'];?></option> 	
					<?php }
					?>                               
					</select>
					<span id="tagsError" class="error"></span>
                  </div>
				 </div>
				  
                <div class="col-sm-4" style="display:<?=($this->userInfo->user_type!='user')?'block':'none'?>">
				<div class="form-group">
                 <label for="exampleInputPassword1">Priority</label>
                 <select name="priority" id="priority" class="form-control select2">
                         <?php
                         foreach($this->priorityArr as $priority)
                         {
                         ?>
                          <!--<option value="<?php echo $priority['priority'].'|'.$priority['contact_by'];?>" <?php if($this->QueryInfo['priority']==$priority['priority']){ ?> selected="selected" <?php }?>><?php echo $priority['priority'];?></option>-->
                          
                        <option value="<?php echo $priority['priority'].'|'.$priority['follow_up_day'].'|'.$priority['contact_by'];?>" <?php if($this->QueryInfo['priority']==$priority['priority']){ ?> selected="selected" <?php }?>><?php echo $priority['priority'];?></option> 
                          <?php }?>
                 </select>
				 
				 <span id="priorityError" class="error"></span>
                </div>
				</div>
				 
                
                <div class="col-sm-4" style="display:none;">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Number of Follow up Day</label>
                 <input type="text" name="no_day" id="no_day" value="<?php //echo $this->QueryInfo['no_day'];?>" class="form-control" />
                </div>
                </div>
                <!--<div class="col-sm-4" style="display:none;">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Word Count</label>
                 <input type="text" name="word_count" id="word_count" value="<?php echo $this->QueryInfo['word_count'];?>" class="form-control" />
                </div>
                </div>-->
                
               <!-- <div class="col-sm-4" style="display:none;">
                <div class="form-group">
                 <label for="exampleInputPassword1">Deadline</label>
                 <input type="text" name="deadline" id="deadline" value="<?php echo $this->QueryInfo['deadline'];?>" class="form-control tcal" />
                </div>
                </div>-->
                <div class="col-sm-4"  style="display:<?=($this->QueryInfo['entrytype']=='PhD')?'block':'none'?>">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Academic Level</label>
                 <input type="text" name="academic_level" id="academic_level" value="<?php echo $this->QueryInfo['academic_level'];?>" class="form-control" />
                </div>
                </div>
               <!-- <div class="col-sm-4" style="display:none;">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Approx Value of Lead</label>
				 <select name="approx_value" id="approx_value" class="form-control">
				<option value="">Please Select</option>
				<option value="Rs.7500-10000"<?php if($this->QueryInfo['approx_value']=="Rs.7500-10000"){ ?> selected="selected" <?php }?>>Rs.7500-10000</option>
				<option value="Rs. 10000-20000"<?php if($this->QueryInfo['approx_value']=="Rs. 10000-20000"){ ?> selected="selected" <?php }?>>Rs. 10000-20000</option>
				<option value="Rs. 20000-50000"<?php if($this->QueryInfo['approx_value']=="Rs. 20000-50000"){ ?> selected="selected" <?php }?>>Rs. 20000-50000</option>
				<option value="Rs. 60000-80000"<?php if($this->QueryInfo['approx_value']=="Rs. 60000-80000"){ ?> selected="selected" <?php }?>>Rs. 60000-80000</option>
				<option value="Rs. 80000-100000"<?php if($this->QueryInfo['approx_value']=="Rs. 80000-100000"){ ?> selected="selected" <?php }?>>Rs. 80000-100000</option>
				<option value="Rs. 100000-150000"<?php if($this->QueryInfo['approx_value']=="Rs. 100000-150000"){ ?> selected="selected" <?php }?>>Rs. 100000-150000</option>
				</select>
				 
				 
                 </div>
                </div>-->
				
                <div class="col-sm-4">
				<div class="form-group">
                 <label for="exampleInputPassword1">Remarks</label>
 				  <textarea name="remarks" id="remarks" class="form-control" <?=($this->userInfo->user_type!='user')?'':'readonly'?> ><?php echo $this->QueryInfo['remarks'];?></textarea>
                </div>
                </div>
               <!-- <div class="col-sm-2" style="display:none;">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Flag Mark</label>
                 <input type="checkbox" name="flag_mark" id="flag_mark" <?php if($this->QueryInfo['flag_mark']=='on'){?> checked="checked" <?php }?> />
                </div>
                </div>
               <div class="col-sm-2" style="display:none;">
               <div class="form-group">
                 <label for="exampleInputPassword1">SMS Notification</label>
                 <input type="checkbox" name="sms_notify" id="sms_notify"  />
                </div>
                </div>
				<div class="col-sm-2" style="display:none;">
				<div class="form-group">
                 <label for="query_type">Old Query</label>
                 <input type="checkbox" name="query_type" id="query_type" value="1" <?php if($this->QueryInfo['query_type']==1){?> checked="checked" <?php }?>   />
                </div>
                </div>
               -->
               <!--  <div class="col-sm-12" style="display:none;">
				 <label for="exampleInputPassword1">Upload File</label>
                 <div class="row" id="attachment_file">
				 
				 <div class="form-group">
                                            <div class="col-md-10"><input type="file" class="form-control" name="upload_file[]" id="upload_file1"/></div>
                                            <div class="col-md-2" id="add_more_button">
											<i style="font-size:20px;padding-top:3px;cursor:pointer;" class="fa fa-plus-circle"></i></div>
              

				 </div>
				 </div>
                </div>-->
				
				 <div class="col-sm-12">
				<?php
				foreach($this->QueryFilesData as $files)
				{ ?>
				<label for="exampleInputPassword1"><a href="<?=SITEURL?><?=$files['file_path'];?>" download><?=$files['filename'];?></a></label><br>
				<?php }
				?>
				
                </div>
				
				
 				
				
              </div>
              <!-- /.box-body -->
          <?php 
            //if(isset($this->userInfo->id) and $this->userInfo->user_type!='user'){ 
		    ?>
              <div class="box-footer">
                 <input type="submit" name="submitBtn" id="submitBtn" class="btn btn-primary" value="Submit" onclick="return ValidateEditQuery();" />
				 
				 &nbsp;&nbsp;
				  <input type="button" class="btn bg-maroon" onClick="parent.location='<?=SITEURL?>managequery/userquery'"  value="Cancel" />
              </div>
              <?php //}?>
            </form>
          </div>
          <!-- /.box -->

       

        </div>
        <!--/.col (left) -->
        <!-- right column -->
         
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>

<script src="<?=PUBLICURL?>bootstrap/js/jquery.js"></script>
   
  <script type="text/javascript">
   $(document).ready(function(){
	 	
  var max_fields_limit      = 10; //set limit for maximum input fields
    var x = 1; //initialize counter for text box
    $('#add_more_button').click(function(e){ //click event on add more fields button having class add_more_button
        e.preventDefault();
        if(x < max_fields_limit){ //check conditions
            x++; //counter increment
			var html="";
			
			
			html+='<div class="form-group"><div class="col-md-10"><input type="file" class="form-control" name="upload_file[]" id="upload_file'+x+'"/></div>';
            html+='<div class="col-md-2" id="remove_field"><i style="font-size:20px;padding-top:3px;cursor:pointer;" class="fa fa-minus-circle"></i></div></div>';
			
			
            $('#attachment_file').append(html); //add input field
        }
    });


$('#attachment_file').on("click","#remove_field", function(e){ //user click on remove text links
        e.preventDefault(); $(this).parent('div').remove(); x--;
    })	
	changeTeam();

	   
   })
  function ValidateEditQuery()
  {  
 var error="";
 var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
  
  if($("#name").val()=="")
  {
	$("#nameError").html("Please enter name");
	document.getElementById("name").focus();
	error=1;
  }	 
  if($("#email_id").val()=="")
  {
	$("#email_idError").html("Please enter email ID");
	document.getElementById("email_id").focus();
	error=1;
  }	  
 else if (reg.test($("#email_id").val()) == false) 
    {
    $("#email_idError").html("Invalid Email Address");
	document.getElementById("email_id").focus();
	error=1;
    }
    if($("#website").val()=="")
  {
	$("#websiteError").html("Please select website");
	document.getElementById("website").focus();
	error=1;
  }	 
  if($("#website").val()==42 && $("#other_website").val()=="" )
  {
	$("#other_websiteError").html("Please enter other website");
	document.getElementById("other_website").focus();
	error=1; 
  }
    if($("#date").val()=="")
  {
	$("#dateError").html("Please select date");
	document.getElementById("date").focus();
	error=1;
  }	
  if($("#requirement").val()=="")
  {
	$("#requirementError").html("Please select service");
	document.getElementById("requirement").focus();
	error=1;
  }
  if($("#requirement").val()==20 && $("#other_requirement").val()=="" )
  {
	$("#other_requirementError").html("Please enter other requirement");
	document.getElementById("other_requirement").focus();
	error=1; 
  }
   if($("#team_id").val()=="")
  {
	$("#team_idError").html("Please seletct team");
	document.getElementById("team_id").focus();
	error=1;
  }
   if($("#allocated_to").val()==null || $("#allocated_to").val()=="")
  {
	$("#allocated_toError").html("Please seletct allocated to user");
	document.getElementById("allocated_to").focus();
	error=1;
  }	  
    if($("#profile_id").val()=="")
  {
	$("#profile_idError").html("Please seletct profile");
	document.getElementById("profile_id").focus();
	error=1;
  }
 
  if($("#priority").val()=="")
  {
	$("#priorityError").html("Please select priority");
	document.getElementById("priority").focus();
	error=1;
  }

 
 if(error==1)
{
return false;
}
else
{
	return true;
}
 
 }
  
  
function OtherFunction()
{
if($("#website").val()==42)
  {	
   $("#other_website_div").show();
  }
  else
  {
 	 $("#other_website_div").hide();  
 }
}


 
function otherRequirement()
{
if($("#requirement").val()==20)
  {	
   $("#other_requirement_div").show();
  }
  else
  {
	  $("#other_requirement").val("");
	 $("#other_requirement_div").hide();  
 }
}
function changeTeam()
{
var team_id=$("#team_id").val();
$.ajax({
    type : 'POST',
    url : '<?php echo SITEURL?>manageuser/index/teamuser',
    data : "team_id="+team_id,
	cache:false,
	beforeSend: function()
	{
    $("#allocated_to").html('<option value="">Loading...</option>');
	},
	success: function(response)
	{
    $("#allocated_to").html(response);
	$("#allocated_to").val(<?=$this->QueryInfo['user_id']?>);
	$("#allocated_to").val(<?=$this->QueryInfo['user_id']?>).trigger("change");
     changeAllocateUser();
	}
  });	
}
function changeAllocateUser()
{
var user_id=$("#allocated_to").val();
$.ajax({
    type : 'POST',
    url : '<?php echo SITEURL?>manageuser/index/getuserprofile',
    data : "user_id="+user_id,
	cache:false,
	beforeSend: function()
	{
    $("#profile_id").html('<option value="">Loading...</option>');
	},
	success: function(response)
	{
    $("#profile_id").html(response);
	
	<?php if($this->QueryInfo['profile_id']){?>
    $("#profile_id").val(<?=$this->QueryInfo['profile_id']?>);
	<?php }?>

	}
  });	
}

</script>