<?php 
 $date = new Zend_Date();
$statusObj = new Managequery_Model_Status();



?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
 								<th>Sr. No.</th>
                                <th>Client Name</th>
								<th>Email ID</th>
                                <th>Phone</th>
                                 <th>City</th>
                                <th>Website</th>
                                 <th>Status</th>
                                 <th>Created Date</th>
    							</tr>
                         
                          <?php $i=1;
 						 
                          foreach($this->QueryData as $Query)
						  {
							 $statusInfo=$statusObj->FetchStatusName($Query['update_status']); 
						  ?>
                                <tr>
                                <td><?=$i;?></td>
								
                                <td><?php echo $Query['name'];?></td>
								<td><?php echo $Query['email_id'];?></td>
                                <td><?php echo $Query['phone'];?></td>
                                 <td><?php echo $Query['location'];?></td>
                                <td><?php if($Query['website']=="others"){ echo $Query['other_website'];} else {
									echo $Query['website'];
								}?></td>
                              <td><?php echo $statusInfo['status_name'];?></td>
                                  
    								<td><?php echo date("M d, Y",$Query['created_on']);?></td>
							</tr>
                         <?php $i++; }?>
  						</table>