<?php $this->userObj = new Manageuser_Model_Manageuser(); 
 $date = new Zend_Date();
$statusObj = new Managequery_Model_Status();



?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
 								<th>Sr. No.</th>
								<th>Ref. Id</th>
								<th>Query Code</th>
								<th>Assign User</th>
                                <th>Client Name</th>
								<th>Email ID</th>
                                <th>Phone</th>
                                 <th>City</th>
                                <th>Website</th>
                                 <th>Requirement</th>
                                <th>Priority</th>
                                 <th>Status</th>
                                 <th>Created Date</th>
    							</tr>
                         
                          <?php $i=1;
 						 
                          foreach($this->queryArr as $Query)
						  {
							 $statusInfo=$statusObj->FetchStatusName($Query['update_status']); 
						  ?>
                                <tr>
                                <td><?=$i;?></td>
								<td><?php echo $Query['assign_id'];?></td>
								<td><?php echo $Query['query_code'];?></td>
								<td><?php echo $Query['username'];?></td>
                                <td><?php echo $Query['name'];?></td>
								<td><?php echo $Query['email_id'];?></td>
                                <td><?php echo $Query['phone'];?></td>
                                 <td><?php echo $Query['city'];?></td>
                                <td><?php if($Query['website']=="others"){ echo $Query['other_website'];} else {
									echo $Query['website'];
								}?></td>
                                 <td><?php if($Query['service_name']=="Other"){ echo $Query['other_requirement'];} else {
									echo $Query['service_name'];
								}?></td>
                                 <td><?php echo $Query['priority'];?></td>
  
                                   <td><?php echo $statusInfo['status_name'];?></td>
                                  
    								<td><?php echo date("M d, Y",$Query['created_on']);?></td>
							</tr>
                         <?php $i++; }?>
  						</table>