<?php 
$date = new Zend_Date();
$this->QueryObj = new Managequery_Model_Managequery();
$this->userObj = new Manageuser_Model_Manageuser();
 $statusObj = new Managequery_Model_Status();
 
 
 ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
 								<th>Sr. No.</th>
								<th>Query Code</th>
                                 <th>Name</th>
								<th>Email ID</th>
                                <th>Phone</th>
                                  <th>City</th>
                                <th>Website</th>
                                 <th>Requirement</th>
                                <th>Allocated to</th>
                                <th>Priority</th>
                                  <th>Status</th>
                                <th>Follow up Date</th>
                                 
                                <th>Created Date</th>
    							</tr>
                         
                          <?php $i=1;
                          foreach($this->queryArr as $Query)
						  {
							  $userinfo= $this->QueryObj->FetchQueryUser($Query['id']);
								$j=1;
  						  ?>
                                <tr>
                                <td><?=$i;?></td>
								<td><?php echo $Query['query_code'];?></td>
								 
                                <td><?php echo $Query['name'];?></td>
								<td><?php echo $Query['email_id'];?></td>
                                <td><?php echo $Query['phone'];?></td>
                                  <td><?php echo $Query['city'];?></td>
                                <td>
								<?php if($Query['website']=="others"){ echo $Query['other_website'];} else {
									echo $Query['website'];
								}?></td>
                                 <td> <?php if($Query['requirement']=="Other"){ echo $Query['other_requirement'];} else {
									echo $Query['requirement'];
								}?> </td>
								<td><?php
								foreach($userinfo as $user)
								{ ?>
								 <?php echo $user['username'];?>
                                 <?php 
								 if(count($userinfo) > $j)
								 {
								  echo ",  ";	 
								 }
								 $j++;
								}
								 ?></td>
                                <td><?php echo $Query['priority'];?></td>
                                 <td><?php echo $statusInfo['status_name'];?></td>
                                <td><?php echo date("M d, Y",$Query['follow_up_date']);?></td>
     								<td><?php echo date("M d, Y",$Query['created_on']);?></td>
							</tr>
                         <?php $i++; }?>
  						</table>