<?php  $date = new Zend_Date();
$this->userObj = new Manageuser_Model_Manageuser();
?>
 
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.0/css/buttons.dataTables.min.css">
<style>
p.message {
    margin-top: -35px;
}.custom-comments-message {
    margin-left: 41px;
}.item {
    border-bottom: 1px solid #f1f1f1;
    margin-bottom: 10px;
    padding-bottom: 0px !important;
}.item i {
    color: orange;
}.nav-tabs-custom>.nav-tabs>li.active {
    border-top: none;
}
</style>
 <form name="form1" id="form1" method="post" action="">
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    
    
    
    
    <section class="content-header">
      <h1>
        Query History
       </h1>
        

   </section>
    
	<section class="content1">
	<?=$this->successmessage?>
        <table class="table table-bordered table-striped table-responsive">
       <tr>
	   <td style="display:<?=($this->userInfo->user_type!='user')?"block":"none"?>"><select name="search_team_id" id="search_team_id" class="form-control select2">
           <option value="">Select Team</option>
           <?php
           foreach($this->teamsArr as $team)
		   {
		   ?>
           <option value="<?php echo $team['id'];?>"><?php echo ucwords($team['team_name']);?></option>
     <?php }?>
           </select>
       </td>
	   
	   
       
       <td>
	   <select name="user_id" id="user_id" class="form-control select2">
           <option value="">Select user</option>
           <?php
           foreach($this->userArr as $users)
		   {
		   ?>
           <option value="<?php echo $users['id'];?>" <?php if($this->userid==$users['id']){ ?> selected="selected" <?php }?>><?php echo ucwords($users['name']);?></option>
           <?php }?>
           </select>
       </td>
      
       <td> <input type="text" value="<?php echo $this->filter_date;?>" name="filter_date" id="filter_date" class="form-control pull-right"  placeholder="From Date - To Date" > 
        </td>
        
        <td> <input type="text" value="<?php echo $this->search_keywords;?>" name="search_keywords" id="search_keywords" class="form-control" placeholder="Enter Keywords Name or Email or Phone">
       </td>
      <td><input type="text" class="form-control" name="ref_id" placeholder="Enter Ref. Id" style="width: 110px;"></td>
        
        <td><select name="website[]" id="website" multiple class="form-control select2" data-placeholder="Select Website">
           <option value="">Select Website</option>
          <?php
                 foreach($this->WebsiteData as $Website)
				 { ?>
					<option value="<?php echo $Website['id'];?>" <?php if($this->website==$Website['id']){ ?> selected="selected" <?php }?>><?php echo $Website['website'];?></option>
                    
				<?php  }
				 ?>
            </select>
       </td>
	   
	   <td><select name="tags[]" id="tags" multiple class="form-control select2" data-placeholder="Select Tags">
           <option value="">Select Tags</option>
          <?php
                 foreach($this->tagsArr as $tag)
				 { ?>
					<option value="<?=$tag['id'];?>" <?=($this->tag==$tag['id'])?"selected":""?>><?=$tag['tag_name'];?></option>
                    
				<?php  }
				 ?>
            </select>
       </td>
	   
	   
         <td>
            <select name="update_status" id="update_status" class="form-control">
            <option value="">Select Status</option>
		   <?php
		   foreach($this->updateStatus as $statusData)
		   { if($statusData['id']!=4)
			   {
		   ?>
		   <option value="<?=$statusData['id']?>" <?php if($statusData['id']==$this->update_status){ ?> selected="selected" <?php }?>><?=$statusData['status_name']?></option>
		   <?php } }?>
		   </select>
         
       </td>
     <td style="display:<?=($this->userInfo->user_type=='user')?"none":"block"?>"><select name="transfer_type" id="transfer_type" class="form-control">
	       
           <option value="" selected>Select All</option>
		   <option value="Fresh">Fresh</option>
		   <option value="1">Transferred</option>
		   <option value="2">Replicated</option>
           </select>
       </td>
          
        <td> <input type="button" name="searchBtn" id="searchBtn" class="btn btn-primary" value="Search" onclick="return ValidateSearch();">
       </td>
      
       </tr> 
       
       
       
       </table>
      
	   </section>
    

	<!-- Main content -->
    <section class="content">
    
      <div class="row">
        <div class="col-xs-12">
		<?php if($this->userInfo->id!=178){?>
		
		<?php if($this->userInfo->user_type!='user'){?>
		<?php if($this->userArr and count($this->userArr) > 0){?>
		<table class="table table-bordered table-striped table-responsive" style="width:30%;">
       <tr>
       
       <td><select name="team_id" id="team_id" class="form-control select2" style="width:200px;" onchange="changeTeam()">
           <option value="">Select Team</option>
           <?php
           foreach($this->teamsArr as $team)
		   {
		   ?>
           <option value="<?php echo $team['id'];?>"><?php echo ucwords($team['team_name']);?></option>
     <?php }?>
           </select>
       </td>
	    <td><select name="assign_user_id" id="assign_user_id" class="form-control select2" style="width:200px;" onchange="changeAllocateUser()">
           <option value="">Select User</option>
           </select>
       </td>
	    <td><select name="profile_id" id="profile_id" class="form-control" style="width:200px;">
           <option value="">Select Profile</option>
           </select>
       </td>
	   
	   <td><select  name="add_tags[]" id="add_tags" multiple class="form-control select2" style="width:200px;" data-placeholder="Select Tags">
           <option value="">Select Tags</option>
           <?php
                 foreach($this->tagsArr as $tag)
				 { ?>
           <option value="<?=$tag['id'];?>"><?=$tag['tag_name'];?></option>]
     <?php }?>
           </select>
       </td>
	   
	    <td> <input type="button" name="searchBtn" id="searchBtn" class="btn btn-primary" value="Transfer Queries" onclick="javascript:ValidateAssignUser();" >
		</td>
	   
	    <td>
		<input type="button" name="searchBtn" id="searchBtn" class="btn btn-primary" value="Replicate Queries" onclick="javascript:ValidateReplicateQueries();" >
 
       </td>
        
       </tr> 
 
       </table>
		<?php }?>
		<?php }?>
   
		<?php } ?>
   
   <div class="row">
   <div class="pull-right">
        <?php
         if(isset($this->userInfo->id) and $this->userInfo->user_type!='user' and $this->userInfo->id!=178)
		 { 
		?>
         <span> <input class="btn btn-danger btn-sm btn-flat" type="button" value="Delete"  onclick="javascript:delRecord();" > &nbsp;</span>
         <?php }?>
		 
         
		 <?php
		 
		 if($this->userInfo->id==178)
		 {
		 ?>
        <span> <input class="btn btn-primary btn-sm btn-flat" type="button" value="Export Email Campaign"  onclick="javascript:ExportEmailCampaignRecord();" > &nbsp;</span>
		
		<span> <input class="btn btn-primary btn-sm btn-flat" type="button" value="Export All Data"  onclick="javascript:ExportAllRecord();" > &nbsp;</span>
		 <?php	 
		 }
		 else
		 {
         if(isset($this->userInfo->id) and ($this->userInfo->user_type=='admin' or $this->userInfo->user_type=='sub-admin')){ 
		?>
        <span> <input class="btn btn-primary btn-sm btn-flat" type="button" value="Export"  onclick="javascript:ExportRecord();" > &nbsp;</span>
		
		<span> <input class="btn btn-primary btn-sm btn-flat" type="button" value="Export CSV"  onclick="javascript:ExportRecordCSV();" > &nbsp;</span>
		 <?php
		 } 
		 }?>
       
        
          <?php
         if(isset($this->userInfo->id) and $this->userInfo->user_type=='Data Manager'){ 
		?>
        <span> <a class="btn btn-primary btn-sm btn-flat" style="text-decoration:none;" href="<?=SITEURL?>managequery/addquery"><i class="fa fa-plus"></i> Add Query</a> </span>
        <?php }?>
        </div>
      </div>
   <div class="clearfix"></div>
   
           <div class="box pt-2">
            <!-- /.box-header -->
			 
            <div class="box-body" id="load_query_history">
           <div style="text-align:center;"> <img style="height:150px;" src="<?=PUBLICURL?>images/pre-loader-new.gif"></div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
          
        </div>
         
        <div class="col-xs-12 scroll-div" id="SecondDiv"></div>
        
        
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
 
  </div>
     </form>
<!-- End Container -->

<!-- Footer -->

<?php include("js/js-userquery.phtml")?>