<?php //print_r($this->MilestoneInfo);die;
$m_totalPrice=$this->MilestoneInfo['milestone_price']; 
if($this->serviceInfo['discount_type']==1)
{
$DiscountedPrice=($m_totalPrice-($m_totalPrice*$this->serviceInfo['discount_value'])/100);
}
else if($this->serviceInfo['discount_type']==2)
{
$DiscountedPrice=($m_totalPrice-($this->serviceInfo['discount_value'])/count($this->packageMilestoneData));	
}
else
{
$DiscountedPrice=$m_totalPrice;
}

function limitTextWords($content = false, $limit = false, $stripTags = false, $ellipsis = false) 
{
    if ($content && $limit) {
        $content = ($stripTags ? strip_tags($content) : $content);
        $content = explode(' ', $content, $limit+1);
        array_pop($content);
        if ($ellipsis) {
            array_push($content, '...');
        }
        $content = implode(' ', $content);
    }
    return $content;
} 
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>Five Vidya - Order Summary</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="<?=PUBLICURL?>checkout/fivevidya/css/bootstrap.min.css" rel="stylesheet" >
<link href="<?=PUBLICURL?>checkout/fivevidya/css/style.css" rel="stylesheet" >
<link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" rel="stylesheet" >
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style>
      td {
    padding: 0px !important;
    padding-left: 5px !important;
}

th {
    padding: 0px !important;
}i.fa.fa-edit {
    float: right;
    margin-top: 13px;
    margin-left: 5px;
}#panel {
  display: none;
}
ul.package-details {
    border-radius: 3px !important;
    border: 1px solid #ededed;
}

  </style>
</head>
<body class="" style="cursor: auto;">
    <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="packagesContent">
	
	</div>
  </div>
</div>
<section class="header">
	<div class="container">
		<div class="row">
			<div class="col-sm-4"><img src="https://www.fivevidya.com/images/logo.png"></div>
		</div>
	</div>
</section>

<section class="heading-bg">
	<div class="container">
	
		<div class="row">
			<div class="col-sm-12 text-center">
			
			<h2><?=$this->serviceInfo['service_name']?> (<?=$this->serviceInfo['ref_id']?>)</h2>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum <br/> has been the industry's standard dummy text ever since the 1500</p>
			</div>
		</div>
	</div>
</section>

<section class="mt-4">
<div class="container pl-xs-0 pr-xs-0">
	<div class="row">
		<div class="col-sm-7">
		    
		    <div class="con-items">
			<!--
        <div class="item item1 mb-4 selected">
            <div class="con-img">
                <img src="1-3.png" alt="">
            </div>
            <header>
                <h3><i class="fa fa-graduation-cap" aria-hidden="true"></i>
 Basic Package</h3>
              
            </header>
            <div class="row">
            <div class="col-sm-9">
                 <b class="w-100 p-3 pt-2 float-left price">
                        <i class="fa fa-inr" aria-hidden="true"></i> 15,000
                    </b>
                <p class="p-2 text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
has been the industry's standard dummy text ever since the 1500 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
has been the industry's standard dummy text ever since the 1500</p>
<div class="car-insurance-area mt-50">
                                   
                                   
                                </div>


</div>
            <div class="col-sm-3 text-right pr-4"><button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                View Details <i class="fa fa-angle-double-right"></i>
            </button></div>
            </div>
             
            
            
        </div>
        <div class="item item1 mb-4" >
            <div class="con-img">
                <img src="1-3.png" alt="">
            </div>
            <header>
                <h3><i class="fa fa-graduation-cap" aria-hidden="true"></i>
 Popular Package</h3>
              
            </header>
            <div class="row">
            <div class="col-sm-9">
                 <b class="w-100 p-3 pt-2 float-left price">
                        <i class="fa fa-inr" aria-hidden="true"></i> 15,000
                    </b>
                <p class="p-2 text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
has been the industry's standard dummy text ever since the 1500 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
has been the industry's standard dummy text ever since the 1500</p>
<div class="car-insurance-area mt-50">
                                   
                                   
                                </div>


</div>
            <div class="col-sm-3 text-right pr-4"><button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                View Details <i class="fa fa-angle-double-right"></i>
            </button></div>
            </div>
             
            
            
        </div>
      -->
	  <?php
	  foreach($this->packageData as $package)
	  {
	  ?>
	  <div class="item item1 mb-4 <?=($package['id']==$this->packageId)?"selected":""?>" >
           <!-- <div class="con-img">
                <img src="1-3.png" alt="">
            </div>-->
            <header>
                <h3><i class="fa fa-graduation-cap" aria-hidden="true"></i> <?=$package['package_name']?></h3>
              
            </header>
            <div class="row">
            <div class="col-sm-9">
                 <b class="w-100 p-3 pt-2 float-left price">
                        <i class="fa fa-inr" aria-hidden="true"></i> <?=$package['package_price']?>
                    </b>
                <p class="p-2 text-justify"><?=limitTextWords($package['service_scope'],80)?></p>
<div class="car-insurance-area mt-50">
                                   
                                   
                                </div>


</div>
            <div class="col-sm-3 text-right pr-4"><button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="getPackageDetails(<?=$package['id']?>)">
                View Details <i class="fa fa-angle-double-right"></i>
            </button></div>
            </div>
             
            
            
        </div>
      <?php }?>

  </div>
				<div class="container">
				    
				    
    <!--<article class="card">
        <header class="card-header"> My Orders  </header>
        <div class="card-body">
            <h6>Order Description</h6>
         <p>
		 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
		 </p>
            <ul class="row border-top mt-4 pt-4">
                <li class="col-md-12">
                    <figure class="itemside mb-3">
                      
                        <figcaption class="info align-self-center">
                            <p class="title"><strong><i class="fa fa-cogs" aria-hidden="true"></i>
 Service Name :</strong> Questionnaire and Experiments <br></p> 
							 <p class="title"><strong><i class="fa fa-file"></i> File Name :</strong> ABCDFHJ nsme <br></p> 
                        </figcaption>
                    </figure>
                </li>
             
            </ul>
            <hr> <a href="#" class="btn btn-warning" data-abc="true"> <i class="fa fa-chevron-left"></i> Back to Website</a>
        </div>
    </article>-->
</div>
		</div>
		
		<div class="col-sm-5">
		<form name="secure_payment" id="secure_payment" method="post" action="<?=SITEURL?>checkout/index/checkoutproccess">
			<div class="card side">
    <div class="title mb-0 text-left">Personal Details</div>
    <div class="info">
        <!--<div class="row">
            <div class="col-12 pl-0"> <span id="heading">Order ID</span> : <span id="details"><strong>OD45345345435</strong></span> </div>
           
        </div>-->
        
          <div class="row pl-0 pt-2 pb-2">
            <div class="col-4 pl-0 pr-0"> <span id="name"><strong
            ><i class="fa fa-user"></i> Name</strong></span> </div>
            <div class="col-8"> <span id="price"><?=$this->serviceInfo['name']?></span> </div>
        </div>
        
           <div class="row pl-0 pr-0 pt-2 pb-2">
            <div class="col-4 pl-0"> <span id="name"><strong
            ><i class="fa fa-envelope"></i> Email id</strong></span> </div>
            <div class="col-8"> <span id="price"><?=$this->serviceInfo['email_id']?></span> </div>
        </div>
        <?php if($this->serviceInfo['phone']){?>
        <div class="row pl-0 pt-2 pb-2">
            <div class="col-4 pl-0 pr-0"> <span id="name"><strong
            ><i class="fa fa-phone" style="    transform: rotate(
90deg);"></i> Phone No.</strong></span> </div>
            <div class="col-8"> <span id="price"><?=$this->serviceInfo['phone']?></span> </div>
        </div>
        <?php }?>
        
    </div>
    
    
           <div class="col-12 pl-0 pr-0"><div class="title mb-0 text-left">Order Details</div></div>
    <div class="pricing">
       <div class="row">
           
     </div>
          <div class="row">
            <div class="col-6 pl-0"> <span id="name"><strong>Selected Package</strong></span> </div>
            <div class="col-6 text-right pr-0"> <span id="price"><?=$this->servicePackageInfo['package_name']?> <i class='fa fa-edit'  onclick="myFunction()"></i></span> 
            
 <div id="panel" class=" mb-2 float-left w-100">
      <select onchange="changepackage(this.value);">
	  <?php
	  foreach($this->packageData as $package)
	  {
	  ?>
         <option value="<?=base64_encode($package['id'])?>" <?=($package['id']==$this->servicePackageInfo['id'])?"selected":""?>><?=$package['package_name']?></option>
	  <?php }?>
          
     </select>
     

    
 </div>
</div>


 
        </div>
       <div class="row">
            <div class="col-12 pl-0">   <table border="1" cellpadding="5" class="mt-2 mb-2" cellspacing="0" style="border: solid 1px;border-color: #cbcbcb;padding: 10px;     width: 105%;font-size:13px " id="milestoneData">
			<tbody><tr>
			<th> &nbsp; Description</th>
			<th> &nbsp; Milestone Price</th>
			<!--<th> &nbsp; Discounted Price</th>-->
			<th> &nbsp; Status </th>
			</tr>
			
			 <?php $i=1; 
          
			foreach($this->packageMilestoneData as $Milestoneval)
			{
			
			?>
			<tr>
			<td> &nbsp; <?=$Milestoneval['milestone_remark']?></td>
			<td> &nbsp; <?="INR ".$Milestoneval['milestone_price']?></td>
			<!--<td> &nbsp; INR <?php echo $Milestoneval['milestone_price']-($Milestoneval['milestone_price']*$this->serviceInfo['discount_value']/100);?></td>  -->
			<td> <?php if($Milestoneval['status']==1){echo "Paid" ;}else{echo "Pending";} ?>
			</td>
			</tr>
			<?php $i++;}?>
			 
						</tbody></table>
        </div></div>
        <div class="row">
            <div class="col-9 pl-0"> <span id="name"><strong>Payment for <?=$this->MilestoneInfo['milestone_name']?>

</strong></span> </div>
            <div class="col-3 text-right"> <span id="price"><i class="fa fa-inr" aria-hidden="true"></i>
<?=$m_totalPrice?></span> </div>
        </div>
        <div class="row">
            <div class="col-9 pl-0"> <span id="name"><strong>Coupon Discount (<?=$this->serviceInfo['coupon_code']?> Auto Applied)

</strong></span> </div>
            <div class="col-3 text-right"> <span id="price"><i class="fa fa-inr" aria-hidden="true"></i>
 (-) <?=($m_totalPrice-$DiscountedPrice)?></span> </div>
        </div>

		 <!-- <div class="row">
            <div class="col-9 pl-0"> <span id="name"><strong>Total Amount</strong></span> </div>
            <div class="col-3 text-right"> <span id="price"><i class="fa fa-inr" aria-hidden="true"></i>
<strong>20,000</strong></span> </div>
        </div>
		 <div class="row">
            <div class="col-9 pl-0"> <span id="name"><strong>GST @ 18%</strong></span> </div>
            <div class="col-3 text-right"> <span id="price"><i class="fa fa-inr" aria-hidden="true"></i>
 2000</span> </div>
        </div>-->
		
		
    </div>
    <div class="total">
        <div class="row">
            <div class="col-9 pl-3">Total Amount to Pay</div>
            <div class="col-3 text-right pr-2"><big><i class="fa fa-inr" style="font-size: 17px;" aria-hidden="true"></i>
<?php
					 echo $DiscountedPrice;
					  ?></big></div>
        </div>
    </div>
    
    
    <div class="row mb-5 pt-0 mt-2 pl-4 pr-4 mt-0">
                                    <div class="col-sm-7 pl-2 pr-0"><h6><strong style="float: left;">Quote Id<input type="text" name="quote_id" id="quote_id" class="form-control mt-2" placeholder="Enter Quote Id" value="" required style=" float: right;
    width: 100%;
    margin-top: 9px !important;"></strong></h6>
</div>
<input type="hidden" name="id" value="<?=$this->serviceInfo['id']?>">
<input type="hidden" name="package_id" value="<?=$this->packageId?>">
									<input type="hidden" name="total_price" value="<?=$DiscountedPrice?>">
                                    <div class="col-md-5 float-right text-right"><div class="tracking">
        <button type="submit" class="btn btn-block btn-outline-primary btn-lg">Proceed to Pay <i class="fa fa-angle-double-right text-light"></i></button> 
    </div></div>
                                </div>
     
</div>
</form>
		</div>
	
	
	</div>
</div>
  </section>
  
  <section class="border-top mt-3 copyright">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 text-center pt-2 pb-2">
				<div class="fot-txt">© 2021 <a class="main-color" href="index.php">Fivevidya.com</a> All Rights Reserved </div>
			</div>
		</div>
	</div>
  </section>
 <style>
 .btn-outline-primary {
    background-color: #0a918b!important;
    color: #FFF !important;
    border-radius: 0.2rem !important;
    border: none !important;
}
 </style>
<script>
function getPackageDetails(pid)
{
$("#packagesContent").html('<div style="text-align:center;padding:10%;"><img src="<?=PUBLICURL?>images/ajax-loader.gif" /></div>');
var url = "<?=SITEURL?>checkout/index/get-package-details"; // the script where you handle the form input.
 $.ajax({
	url: url,
	type: "get",
	data:  {package_id:pid},
	cache: false,
	success: function(data){
	$("#packagesContent").html(data);	 
	},
	error: function(){} 	        
});	
}
</script>


<script>
function myFunction() {
  document.getElementById("panel").style.display = "block";
}
function changepackage(id)
{
var url = "<?=SITEURL?>checkout?id=<?=$this->serviceInfo['id']?>&package="+id;
 window.location = url; // redirect	
}
</script>
</body></html>