<?php
$uploadFileArr=array();
if($this->packageInfo['templateUploadFile'])
{
$uploadFileArr=json_decode($this->packageInfo['templateUploadFile'], true);	
}

$extraFile=array();
if($this->serviceInfo['document_file'])
{
$extraFile=json_decode($this->serviceInfo['document_file'], true);	
}
?>
      
      <div class="modal-body popScroll">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        
<h1>Read About <?=$this->packageInfo['package_name']?></h1>
        <div class="card-body">
            <div class="row back-man">
                <div class="col-sm-7 offset-lg-5">
                    
                     <h6>What is <?=$this->packageInfo['package_name']?></h6>
         <p class="text-justify">
		 <?=$this->packageInfo['service_scope']?>
		 </p>
		<!--  <p class="text-justify pt-1">
		 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry.
		 </p>-->
		  <figure class="itemside mb-3">
                      
                        <figcaption class="info align-self-center pl-0">
                          
							 <p class="title"><!--<strong><i class="fa fa-file"></i></strong>--> 
      <?php if($this->packageInfo['p_file_permission']=='Yes' and $uploadFileArr['file_title_name'] and $uploadFileArr['file_path']!=""){ 
?>
		 <a href="<?=SITEURL?>public/UploadFolder/<?=$uploadFileArr['file_path']?>" download class="download-button"><?=$uploadFileArr['file_title_name']?> <i class="fa fa-download text-light" aria-hidden="true"></i></a>		  
				  
<?php }?>
<?php if(count($extraFile) > 0)
{
	foreach($extraFile as $files)
	{ ?>
		<a href="<?=SITEURL?>public/UploadFolder/<?=$files['file_path']?>" download class="download-button pr-2"><?=$files['filename']?> <i class="fa fa-download text-light" aria-hidden="true"></i></a>	
	<?php }
}	
?>


<br></p> 
                        </figcaption>
                    </figure>
                </div>
                
            </div>
            
            <div class="row mt-3">
                
                <div class="car-insurance mt-50 p-4">
                                    <h4 class="text-center">Why You Should Choose Fivevidya</h4>
                                    <ul class="ul-style-2 pt-3">
                                        <li>Lorem ipsum dolor sit amet, ciit in voluptate velit esse cillum.</li>
                                        <li>Tempor at. Duis aute irure dolor in reprehenderit in voluptate veldolou fugiat nulla paria turat.</li>
                                        <li>Omnis iste natus error sit voluptatem accusantium doloremque laudantiuquae ab illo inventore veritatis et
                                            quasi dolorem.</li>
                                        <li>Do eiusmod tempor incididunt ut labore et dolore masit amet.</li>
                                    </ul>
                                </div>
            </div>
            
           <p class="text-center col-sm-12 align-items-center"><button onclick="javascript:location.href='<?=SITEURL?>checkout?id=<?=$this->packageInfo['service_id']?>&package=<?=base64_encode($this->packageInfo['id'])?>'" type="button" class="proceed-button border-none col-lg-5 float-none ml-0" data-dismiss="modal">Select Package <i class="fa fa-angle-double-right"></i></button></p> <div class="client-panel">
              
              <h3 class="col-sm-12 text-center pb-3">Our Past Clients Were From</h3>
              
                <ul class="mt-2">
<li><img src="<?=PUBLICURL?>checkout/fivevidya/images/walden-university.png" alt="Walden University"></li>
<li><img src="<?=PUBLICURL?>checkout/fivevidya/images/walden-university.png" alt="Walden University"></li>
<li><img src="<?=PUBLICURL?>checkout/fivevidya/images/walden-university.png" alt="Walden University"></li>
<li><img src="<?=PUBLICURL?>checkout/fivevidya/images/walden-university.png" alt="Walden University"></li>
<li><img src="<?=PUBLICURL?>checkout/fivevidya/images/walden-university.png" alt="Walden University"></li>
<li><img src="<?=PUBLICURL?>checkout/fivevidya/images/walden-university.png" alt="Walden University"></li>

</ul>
            </div>
            
            
           
        </div>
    </article>
      </div>
    
  