<?php
$uploadFileArr=array();
if($this->serviceInfo['upload_file'])
{
$uploadFileArr=json_decode($this->serviceInfo['upload_file'], true);	
}
$extraFile=array();
if($this->serviceInfo['document_file'])
{
$extraFile=json_decode($this->serviceInfo['document_file'], true);	
}
?>        
		  <div class="form-group">
                  <label class="col-sm-4 control-label">Service Name</label>
                  <div class="col-sm-8"><?=$this->serviceInfo['quote_service_name']?> 				
                  </div>
                </div>
				<div class="clearfix"></div>
				 <div class="form-group">
                  <label class="col-sm-4 control-label">Discount Value</label>
                  <div class="col-sm-8"><?=$this->serviceInfo['discount_value']?><?=($this->serviceInfo['discount_type']==1)?"%":""?>					
                  </div>
                </div>
				
				<div class="clearfix"></div>
				<div class="form-group">
                  <label class="col-sm-4 control-label">Total Amount</label>
                  <div class="col-sm-8">
				<span id="show_sr_amount_div<?=$this->serviceInfo['id']?>">
			  <?=$this->serviceInfo['total_price']?> 
			 <?php if($this->userInfo->user_type=='user' and $this->serviceInfo['status']==0){?>
			  <span onclick="ChangeServiceAmount(<?=$this->serviceInfo['id']?>)" style="font-size:15px; margin-left: 10px; cursor:pointer;" class="fa fa-edit">
			  </span>
			 <?php }?>
			  </span>
			  <span id="edit_sr_amount_div<?=$this->serviceInfo['id']?>" style="display:none;">
			   <input class="form-control1" style="width:100px;" type="text" name="edit_service_amount<?=$this->serviceInfo['id']?>" id="edit_service_amount<?=$this->serviceInfo['id']?>" value="<?=$this->serviceInfo['total_price']?>">
			   <input class="btn btn-info btn-xs" type="button" onclick="SaveServiceAmount(<?=$this->serviceInfo['id']?>)" value="Save">
			  </span>
				
                				
                  </div>
                </div>
				<div class="clearfix"></div>
				<div class="form-group">
                  <label class="col-sm-4 control-label">Coupon Code</label>
                  <div class="col-sm-8"><?=$this->serviceInfo['coupon_code']?>				
                  </div>
                </div>
				<div class="clearfix"></div>
				<div class="form-group">
                  <label class="control-label">Work Scope  <?php if($this->userInfo->user_type=='user' and $this->serviceInfo['status']==0){?>
									  <span onclick="ChangeWorkScope(<?=$this->serviceInfo['id']?>)" style="font-size:15px; margin-left: 10px; cursor:pointer;" class="fa fa-edit pull-right">
									  </span>
									  <?php }?></label>
                  <div class="col-sm-12">
				  <span id="show_ws_div<?=$this->serviceInfo['id']?>">
									  <?=$this->serviceInfo['order_summary']?>
									  
									  </span>
									  
									  <span id="edit_ws_div<?=$this->serviceInfo['id']?>" style="display:none;">
									   <textarea class="form-control edit_work_scope" name="edit_work_scope<?=$this->serviceInfo['id']?>" id="edit_work_scope<?=$this->serviceInfo['id']?>"><?=$this->serviceInfo['order_summary']?></textarea>
									   <input class="btn btn-info btn-xs pull-right" type="button" onclick="SaveWorkScope(<?=$this->serviceInfo['id']?>)" value="Save">
									  </span>
				  
				  				
                  </div>
                </div>
				
<?php if($this->serviceInfo['file_permission']=='Yes' and $uploadFileArr['file_title_name'] and $uploadFileArr['upload_file']!=""){ 
?>
<div class="clearfix"></div>
				<div class="form-group">
                  <label class="col-sm-4 control-label">Template File</label>
                  <div class="col-sm-8"> <a href="<?=SITEURL?>public/UploadFolder/<?=$uploadFileArr['upload_file']?>" download class="label label-default"><?=$uploadFileArr['file_title_name']?> <i class="fa fa-download text-light" aria-hidden="true"></i></a>
                  </div>
                </div>
				
		  
  
<?php }?>
				
				
			<?php if(count($extraFile) > 0)
{ ?>
<div class="clearfix"></div>
				<div class="form-group">
                  <label class="col-sm-4 control-label">CRM Uploaded File</label>
                  <div class="col-sm-8">
 <?php foreach($extraFile as $files)
		{ ?>
		 <a href="<?=SITEURL?>public/UploadFolder/<?=$files['file_path']?>" download class="label label-default"><?=$files['filename']?> <i class="fa fa-download text-light" aria-hidden="true"></i></a>	
		<?php } ?>
                  </div>
                </div>
<?php } ?>	
				
			 
				
				<?php if($this->serviceInfo['payment_website']!="Other"){?>
				<div class="clearfix"></div>
				<div class="form-group">
                  <label class="col-sm-4 control-label">Payment Url</label>
                  <div class="col-sm-8"><a href="<?=SITEURL?>checkout?id=<?=$this->serviceInfo['id']?>" target="_blank"><?=SITEURL?>checkout?id=<?=$this->serviceInfo['id']?></a>				
                  </div>
                </div>
				<?php } ?>
				
				<?php if($this->serviceInfo['expiry_date']){?>
				<div class="clearfix"></div>
				<div class="form-group">
                  <label class="col-sm-4 control-label">Expiry Date</label>
                  <div class="col-sm-8"> 
                   <span id="show_expdate_div<?=$this->serviceInfo['id']?>">
									  <?=date("d M, Y",$this->serviceInfo['expiry_date'])?>
									   <?php if($this->userInfo->user_type=='user' and $this->serviceInfo['status']==0){?>
									  <span onclick="ChangeExpiryDate(<?=$this->serviceInfo['id']?>)" style="font-size:15px; margin-left: 10px; cursor:pointer;" class="fa fa-edit">
									  </span>
									  <?php }?>
									  </span>
									  
									  <span id="edit_expdate_div<?=$this->serviceInfo['id']?>" style="display:none;">
									   <input class="form-control datepicker edit_expiry_date" name="edit_expiry_date<?=$this->serviceInfo['id']?>" id="edit_expiry_date<?=$this->serviceInfo['id']?>" value="<?=date("m/d/Y",$this->serviceInfo['expiry_date'])?>">
									   <input class="btn btn-info btn-xs pull-right" type="button" onclick="SaveExpiryDate(<?=$this->serviceInfo['id']?>)" value="Save">
									  </span>


				  			
                  </div>
                </div>
				<?php } ?>
				
				
				<div class="clearfix"></div>
				<br>
			  <div class="form-group">
			  <label class="control-label">Milestone Details</label>
			  <?php if($this->userInfo->user_type=='user' and $this->serviceInfo['status']==0){?>
			  <div class="pull-right"><span class="btn btn-primary btn-sm" onclick="showAddMilestoneDiv(<?=$this->serviceInfo['id']?>)">Add New Milestone</span></div>
			  <?php }?>
                 <table class="table">
                <tr>
                  <th>#</th>
                  <th>Milestone Name </th>
                  <th>Milestone Price</th>
                  <th>Discounted Price</th>
                  <th>ETA</th>
 				  <?php if($this->userInfo->user_type=='user'){?>
                  <th>Action</th>
				  <?php }?>
                </tr>
				
				<?php 
				$i=1;
				$paymentCount=0;
				foreach($this->serviceMilestoneData as $milestones){?>
                <tr>
                  <td><strong><?=$i?>.</strong></td>
                  <td> <?=$milestones['milestone_name']?></td>
                  <td>
				   <span id="show_ml_amount_div<?=$milestones['id']?>">
									  <?=$milestones['milestone_price']?>
									  
									<?php if($this->userInfo->user_type=='user' and $milestones['status']!=1){?>
									<span onclick="ChangeMilestoneAmount(<?=$milestones['id']?>)" style="font-size:15px; margin-left:5px; cursor:pointer;" class="fa fa-edit">
									  </span>
									<?php }?>
									  </span>
									  <span id="edit_ml_amount_div<?=$milestones['id']?>" style="display:none;">
									   <input class="form-control1" style="width:100px;" type="text" name="edit_milestone_amount<?=$milestones['id']?>" id="edit_milestone_amount<?=$milestones['id']?>" value="<?=$milestones['milestone_price']?>">
									   <input class="btn btn-info btn-xs" type="button" onclick="SaveMilestoneAmount(<?=$milestones['id']?>,<?=$milestones['service_id']?>)" value="Save">
									  </span>
				  
				  
				  </td>
				 
                  <td>
				  <?php
				  if($this->serviceInfo['discount_type']==1)
				 {
				   echo $milestones['milestone_price']-($milestones['milestone_price']*$this->serviceInfo['discount_value']/100);
				 }
				 else if($this->serviceInfo['discount_type']==2)
				 {
				   echo $milestones['milestone_price']-($this->serviceInfo['discount_value']/count($this->serviceMilestoneData));	 
				 }
				 else
				 {
					echo $milestones['milestone_price']; 
				 }
				  ?>
				  
				 </td>
				  <td> <?=($milestones['milestone_eta'])?date("d M Y",$milestones['milestone_eta']):""?></td>
                  
				  <?php if($this->userInfo->user_type=='user'){?>
				  <td><?php if($milestones['status']==0){?><a href="javascript:" onclick="DeleteMilestone(<?=$milestones['id']?>,<?=$milestones['service_id']?>)"><i class="fa fa-trash-o"></i></a><?php }?></td>
				  <?php }?>
                </tr>
				
				<tr>
				
				<td colspan="3"> Remarks : <?=$milestones['milestone_remark']?></td>
				<td colspan="3"> Status :  <?php if($this->userInfo->user_type=='user'){?>
		     <select style="width:90px;" name="milestone_status" id="milestone_status<?=$milestones['id']?>" onchange="ChangeMilestoneStatus(<?=$milestones['service_id']?>,<?=$milestones['id']?>,this.value)" <?=($milestones['status']==1)?"disabled":""?> >
			 <option value="1" <?=($milestones['status']==1)?"selected":""?>>Paid</option>
			 <option value="0" <?=($milestones['status']==0)?"selected":""?>>Pending</option>
			 
			 </select>
				  <?php } else {   
				      if($milestones['status']==1)
				      {
					  echo '<span class="label label-success">Paid</span>';
					  }
					  else
						{
						echo '<span class="label label-warning">Pending</span>'; 
				        }
				  }
				  
				  
				      if($milestones['status']==1)
				      {
					  $paymentCount=$paymentCount+1;
					  }
					  
				  
				  
				  ?></td>
				</tr>
				
				
				<?php 
				
			 
				$i++; } ?>
               
              </table>
			  
             <div class="clearfix"></div>
			 <div id="milestoneStatusUpdateMess<?=$this->serviceInfo['id']?>">
			 
			 
			 
			 
			 </div>
				  
                </div>
<script>
 $(function () {
  $('.edit_work_scope').wysihtml5();
  
  <?php if($paymentCount > 0){ ?>
  $("#mainServiceDeleteDiv<?=$this->serviceInfo['id']?>").hide();
  <?php }
  else
  { ?>
	$("#mainServiceDeleteDiv<?=$this->serviceInfo['id']?>").show();  
 <?php }?>
  
 });
</script>				