<?php 
date_default_timezone_set("Asia/Kolkata");
$date = new Zend_Date();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$Controller= Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action=Zend_Controller_Front::getInstance()->getRequest()->getActionName();
 $QuoteObj = new Managequote_Model_Managequote();
 $pendingQuoteNoti=$QuoteObj->FetchAllUnreadNotification($this->userInfo->id);
  ?>

<!DOCTYPE html>

<html>

<head>

  <meta charset="utf-8">
 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Query Panel - <?=$this->userInfo->name;?></title>
   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
   <link rel="stylesheet" href="<?=PUBLICURL?>bootstrap/css/bootstrap.min.css">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>dist/css/AdminLTE.min.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>dist/css/skins/_all-skins.min.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/iCheck/flat/blue.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/morris/morris.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/datatables/dataTables.bootstrap.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/jvectormap/jquery-jvectormap-1.2.2.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/datepicker/datepicker3.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/daterangepicker/daterangepicker-bs3.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/timepicker/bootstrap-timepicker.min.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/datepicker/datepicker3.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/select2/select2.min.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>plugins/morris/morris.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>dist/css/tcal.css">
   <link rel="stylesheet" href="<?=PUBLICURL?>dist/css/style.css">
  </head>

<body class="hold-transition skin-blue sidebar-mini">

  <link rel="stylesheet" type="text/css" href="<?=PUBLICURL?>stiky_notes/styles.css" />

<link rel="stylesheet" type="text/css" href="<?=PUBLICURL?>stiky_notes/fancybox/jquery.fancybox-1.2.6.css" media="screen" />



<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>

 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>

<script type="text/javascript" src="<?=PUBLICURL?>stiky_notes/fancybox/jquery.fancybox-1.2.6.pack.js"></script>

 <script type="text/javascript" src="<?=PUBLICURL?>stiky_notes/script.js"></script>

 

  <link rel="stylesheet" href="<?=PUBLICURL?>ajaxify/css/normalize.min.css">

  <link rel="stylesheet" href="<?=PUBLICURL?>ajaxify/css/main.css">

  <script src="<?=PUBLICURL?>ajaxify/js/vendor/modernizr-2.6.2.min.js"></script>

  <?php echo $notes_value;?>

  <div class="wrapper">

  

  

  <header class="main-header">

    <!-- Logo -->

    <a href="<?=SITEURL?>dashboard" class="logo ajaxify">

        <!-- logo for regular state and mobile devices -->

      <span class="logo-lg">Query Management</span>

    </a>

	
	

    <!-- Header Navbar: style can be found in header.less -->

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">

        <div class="container-fluid"> 

          <!-- Brand and toggle get grouped for better mobile display -->

          <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle Navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>

             

		</div>

          <!-- Collect the nav links, forms, and other content for toggling -->

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav">

              <li><a href="<?php echo SITEURL?>consultant" class="ajaxify"><span class="hidden-xs">Dashboard</span></a></li>

			  <li><a href="<?php echo SITEURL?>consultant/pending-quote" class="ajaxify">Allocations</span></a></li>
        
			  <li><a href="<?php echo SITEURL?>consultant/price-submitted-quote" class="ajaxify">Submissions</span></a></li>
           
            </ul>

	  </div>

	  <div class="navbar-brand">

			<div class="navbar-custom-menu">
 
        <ul class="nav navbar-nav">
<!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning"><?=count($pendingQuoteNoti)?></span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have <?=count($pendingQuoteNoti)?> notifications</li>
              <li>
                 <ul class="menu">
                  <?php foreach($pendingQuoteNoti as $noti){?>
				 <li>
                    <a href="<?=SITEURL?>consultant/index/viewquote/quoteid/<?=$noti['quote_id']?>/noti_id/<?=$noti['id']?>" >
                      <span style="font-weight:bold;"><?=ucwords($noti['name'])?> <span class="pull-right"> Ref. No.(<?=$noti['ref_id']?>)</span> </span>
					  <div><?=$noti['message']?></div>
					  <div><?=date("d M, Y h:i A",$noti['date'])?></div>
                    </a>
					 
                  </li> 
				 
				  <?php } ?>
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li> 
          <!-- Tasks: style can be found in dropdown.less -->
           <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <span class="hidden-xs"><?=$this->userInfo->name;?></span>
            </a>
            <ul class="dropdown-menu">
               <li class="user-footer">
                <div class="pull-left">
                <a href="<?php echo SITEURL?>changepassword" class="btn btn-default btn-flat">Change Password</a>
                 </div>
                <div class="pull-right">
                  <a href="<?php echo SITEURL?>index/logout" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
          </li>
        </ul>
      </div>
		</div>
    </nav>
	</header>
	<!-- Left side column. contains the logo and sidebar -->

   

   <!-- Content Wrapper. Contains page content -->

    <div id="content"> 

   <?=$this->layout()->content;?></div>

  <!-- /.content-wrapper -->

  <footer class="main-footer">

  Powered by EMarketz India Pvt Ltd

     <!--<strong>Copyright &copy; 2015 <a href="http://www.emarketzindia.com" target="_blank">Emarketz India Pvt. Ltd.</a> </strong> All rights

    reserved.-->

  </footer>

 </div>

         
 

<!-- ./wrapper -->
 
<script src="<?=PUBLICURL?>ajaxify/js/vendor/jquery-2.0.3.min.js"></script>

<script src="<?=PUBLICURL?>ajaxify/js/vendor/jquery.history.js"></script>

<script src="<?=PUBLICURL?>ajaxify/js/ajaxify.js"></script>
 
<!-- jQuery 2.1.4 -->

<script src="<?=PUBLICURL?>plugins/jQuery/jQuery-2.1.4.min.js"></script>
 

<!-- jQuery UI 1.11.4 -->

<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<script>

  $.widget.bridge('uibutton', $.ui.button);

</script>

<!-- Bootstrap 3.3.5 -->

<script src="<?=PUBLICURL?>bootstrap/js/bootstrap.min.js"></script>

<!-- Morris.js charts -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>

<script src="<?=PUBLICURL?>plugins/morris/morris.min.js"></script>

<!-- Sparkline -->

<script src="<?=PUBLICURL?>plugins/sparkline/jquery.sparkline.min.js"></script>

<!-- jvectormap -->

<script src="<?=PUBLICURL?>plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>

<script src="<?=PUBLICURL?>plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

<!-- jQuery Knob Chart -->

<script src="<?=PUBLICURL?>plugins/knob/jquery.knob.js"></script>

<!-- daterangepicker -->

<script src="<?=PUBLICURL?>plugins/input-mask/jquery.inputmask.js"></script>

<script src="<?=PUBLICURL?>plugins/input-mask/jquery.inputmask.date.extensions.js"></script>

<script src="<?=PUBLICURL?>plugins/input-mask/jquery.inputmask.extensions.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>

<script src="<?=PUBLICURL?>plugins/daterangepicker/daterangepicker.js"></script>

<!-- datepicker -->

<script src="<?=PUBLICURL?>plugins/timepicker/bootstrap-timepicker.min.js"></script>

<script src="<?=PUBLICURL?>plugins/datepicker/bootstrap-datepicker.js"></script>



<!-- Bootstrap WYSIHTML5 -->

<script src="<?=PUBLICURL?>plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

<!-- Slimscroll -->

<script src="<?=PUBLICURL?>plugins/slimScroll/jquery.slimscroll.min.js"></script>

<!-- FastClick -->

<script src="<?=PUBLICURL?>plugins/fastclick/fastclick.js"></script>

<!-- AdminLTE App -->



<!-- AdminLTE dashboard demo (This is only for demo purposes) -->

<!--<script src="<?=PUBLICURL?>dist/js/pages/dashboard.js"></script>-->

<!-- AdminLTE for demo purposes -->

<script src="<?=PUBLICURL?>dist/js/demo.js"></script>

 <script src="<?=PUBLICURL?>plugins/select2/select2.full.min.js"></script>

<script src="<?=PUBLICURL?>plugins/timepicker/bootstrap-timepicker.min.js"></script>

 

<script src="<?=PUBLICURL?>plugins/datatables/jquery.dataTables.min.js"></script>

<script src="<?=PUBLICURL?>plugins/datatables/dataTables.bootstrap.min.js"></script>



<script src="<?=PUBLICURL?>dist/js/tcal.js"></script>

 <link rel="stylesheet" href="<?=PUBLICURL?>colorbox/colorbox.css" />

 <script src="<?=PUBLICURL?>colorbox/jquery.colorbox.js"></script>
 
 
<script>

  $(function () {
  	/* $('#fromdate').datepicker();
	  $('#todate').datepicker();
	  $('#date').datepicker();
	  $('#remainder_date').datepicker();*/ 
	  $('#filter_date').daterangepicker();
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": true
    });
	 $(".select2").select2();
	  //Timepicker
    $(".timepicker").timepicker({
      showInputs: false
    });
	 $(".datepicker").datepicker({
      showInputs: false
    });
 
 $("input").keypress(function(){
 var id=this.id;
 $("#"+id+"Error").html('');
});
$("textarea").keypress(function(){
 var id=this.id;
 $("#"+id+"Error").html('');
});
 $("input").click(function(){
 var id=this.id;
 $("#"+id+"Error").html('');
});
 $("select").change(function(){
 var id=this.id;
 $("#"+id+"Error").html('');
});


   });

</script>

 

 </body>

</html>

 