<div class="box box-warning">
            <div class="box-header with-border">
              <h3 class="box-title">Chat</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <!-- Conversations are loaded here -->
              <div class="direct-chat-messages" id="chat_content">
			                  <!-- /.direct-chat-msg -->
              </div>
              <!--/.direct-chat-messages-->

             
            </div>
            <!-- /.box-body -->
			<?php if($this->userInfo->user_type=='admin' or $this->userInfo->user_type=='user'){?>
			 <form class="form-horizontal" id="submitchat" name="submitchat" method="POST">
            <div class="box-footer">
          
                <div class="input-group" style="width:100%;">
                  <input type="text" name="message" id="message" placeholder="Type Message ..." class="form-control" style="height:34px;">
                   <input type="hidden" name="quote_ids" value="<?=$this->quoteInfo['id']?>" id="quote_ids">
                   <input type="hidden" name="ref_id" value="<?=$this->quoteInfo['ref_id']?>" id="ref_id">
                      <span class="input-group-btn" id="chatLoadBtn">
					  <input type="button" name="sibmitchatforuser" id="sibmitchatforuser" value="Send" class="btn btn-warning btn-flat" style="margin-top:-10px;">
                      </span>
                </div>
             
            </div>
			 </form>
			<?php }?>
            <!-- /.box-footer-->
          </div>
					