<style>
	.tab-scetion {
    margin: 0;
	border-bottom:none;
		margin-bottom: 20px;
}
	.tab-scetion li {
    background: #ddd;
}
	.tab-scetion li a{
	padding: 7px 20px;
    margin: 0;
	}
	.tab-scetion li:active a, .tab-scetion li:active{
	background: #f39c12 !important;
	}
	.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover{
		background-color: #f39c12 !important;
		color:#fff !important;
	}
</style>
<div class="col-md-10">
<?php if(count($this->ArchiveData) > 0){?>
<ul class="nav nav-tabs tab-scetion">
<?php foreach($this->ArchiveData as $data){?>
<li id="archiveList<?=$data->archive_no?>"><a style="color:#444;border-radius:0;" href="#" data-toggle="tab" onclick="getArchiveComments(<?=$data->archive_no?>)">Archive <?=$data->archive_no?></a></li>
<?php } ?>

</ul>
<?php }?>
</div>
<div class="col-md-2">
<?php if(count($this->UnArchiveData) > 0){?>
<button style="margin: 0px;
    padding: 8px;
    font-size: 11px;
    float: right;" type="button" class="btn btn-primary btn-sm" onclick="return saveCommentsArchive(<?=$this->assign_id?>)">Save Archive</button>
<?php }?>
</div>