<?php
 $this->QueryDashboardObj = new Dashboard_Model_Managequery();
 ?>
 
 <?php 
 //echo "<pre>";
//print_r($this->DelayData);
 //echo "</pre>";
 ?>
 <style>
 .td_title{
	 width:30%;color: brown;padding: 3px;
 }
 .td_title th{ padding:4px;text-align:center;}
 </style>
 <div class="row" style="margin-top:-20px !important;">
 <div class="col-md-2"  id="ConversionBtn"><a href="javascript:" class="label label-info pull-right" onclick="showConversionSummary()">Show Conversion Summary</a></div>
 
  <div class="col-md-2" style="margin-top:-5px;"><a href="<?=SITEURL?>managequery/client-mail" target="_blank" class="label label-info">Show my mailbox<span class="label label-warning ClientTotalUnraed"><?=$this->notUnread['ClientTotalUnraed']?></span></a></div>
  </div>
 <div class="row" id="showConversionSummaryDiv">
 
 </div>
 
 
   
  <div class="clear-fix"></div>
   <div class="row">
   
   <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Today’s Tasks (<?=count($this->todayTask)?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-2">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable3">
               <?php
             foreach($this->todayTask as $task)
			 {
			 ?>
               <li id="<?=$task['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$task['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title"  data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$task['email_id']?>"><?=$task['name']?>
					
					
					
                      
					   <?php if($task['update_status']==1)
						  {
							 echo '<span class="label label-info pull-right">Lead In</span>'; 
						  }
						  else if($task['update_status']==2)
						  {
							 echo '<span class="label label-primary pull-right">Contact Made</span>'; 
						  }
						  else if($task['update_status']==3)
						  {
							 echo '<span class="label label-warning pull-right">Quoted</span>'; 
						  }
						  else if($task['update_status']==4)
						  {
							 echo '<span class="label label-default pull-right">Negotiating</span>'; 
						  }
						  else if($task['update_status']==5)
						  {
							 echo '<span class="label label-success pull-right">Converted</span>'; 
						  }
						  else if($task['update_status']==6)
						  {
							 echo '<span class="label label-danger pull-right">Client Not Interested</span>'; 
						  }
						  else if($task['update_status']==7)
						  {
							 echo '<span class="label label-info pull-right">Reminder</span>'; 
						  }
						  ?>
					  </a>
					  
					  
					  
					  
                        <span class="product-description">
 						   	 Ref. No. : <?=$task['assign_id']?> 
							 <?php if($task['assign_follow_up_date']){?>
							<div>Due since:<?=date("d M Y",$task['assign_follow_up_date'])?></div> 
							 <?php }?>
							<?php 
							if($task['open_date']!="" and $task['open_status']==0){
								echo '<div class="timerCls"><a href="javascript:void(0)" style="color:red" data-placement="bottom" data-toggle="tooltip" data-original-title="'.date("d M Y h:i A",$task['open_date']).'">Due since:'.$this->QueryDashboardObj->GetdateTimeFormate($task['open_date']).'</a></div>';
							}
								?>
 						  
						 
						 
                        </span>
                  </div>
                </li>
                
              <?php }?>
                </ul>
				<div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
		
		       
        <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-warning">
            <div class="box-header with-border">
              <h3 class="box-title">Open tasks (<?=count($this->openTask)?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-3">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable3">
               <?php
             foreach($this->openTask as $task)
			 {
			 ?>
               <li id="<?=$task['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$task['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$task['email_id']?>"><?=$task['name']?>
					
					<?php if($task['update_status']==1)
						  {
							 echo '<span class="label label-info pull-right">Lead In</span>'; 
						  }
						  else if($task['update_status']==2)
						  {
							 echo '<span class="label label-primary pull-right">Contact Made</span>'; 
						  }
						  else if($task['update_status']==3)
						  {
							 echo '<span class="label label-warning pull-right">Quoted</span>'; 
						  }
						  else if($task['update_status']==4)
						  {
							 echo '<span class="label label-default pull-right">Negotiating</span>'; 
						  }
						  else if($task['update_status']==5)
						  {
							 echo '<span class="label label-success pull-right">Converted</span>'; 
						  }
						  else if($task['update_status']==6)
						  {
							 echo '<span class="label label-danger pull-right">Client Not Interested</span>'; 
						  }
						  else if($task['update_status']==7)
						  {
							 echo '<span class="label label-info pull-right">Reminder</span>'; 
						  }
						  ?>
					
					
					
                       </a>
                        <span class="product-description">
 						   Ref. No. : <?=$task['assign_id']?>
						  
						  <?php if($task['open_date']!="" and $task['open_status']==0){
							  echo '<div class="timerCls"><a href="javascript:void(0)" style="color:red" data-placement="bottom" data-toggle="tooltip" data-original-title="'.date("d M Y h:i A",$task['open_date']).'">Due since:'.$this->QueryDashboardObj->GetdateTimeFormate($task['open_date']).'</a></div>';
						  } else if($task['update_status']==7){
							echo '<div class="timerCls"><a href="javascript:void(0)" style="color:red" data-placement="bottom" data-toggle="tooltip" data-original-title="'.date("d M Y h:i A",$task['remainder_date']).'">Due since:'.$this->QueryDashboardObj->GetdateTimeFormate($task['remainder_date']).'</a></div>';  
						  }?>
						  
                        </span>
                  </div>
                </li>
                
              <?php }?>
                </ul>
				<div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
		
	   <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-default">
            <div class="box-header with-border">
              <h3 class="box-title"> Escalation  (<?=count($this->escalationTask)?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-4">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable4">
            <?php
             foreach($this->escalationTask as $NegotiatingValue)
			 {
			 ?>
                <li id="<?=$NegotiatingValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$NegotiatingValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$NegotiatingValue['email_id']?>"><?=$NegotiatingValue['name']?> </a>
                        <span class="product-description">
                           Follow up Date : <?=date("d M Y",$NegotiatingValue['assign_follow_up_date'])?>
						  <br>Ref. No. : <?=$NegotiatingValue['assign_id']?>
                        </span>
                  </div>
                </li>
              
              <?php }?>
              </ul>
			  <div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
			   
   
   
   
<div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Lead In (<?=$this->LeadsCount?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-1">
             <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable1">
             <?php 
             foreach($this->LeadsData as $leadValue)
			 {
			 ?>
                <li id="<?=$leadValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$leadValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$leadValue['email_id']?>"><?=$leadValue['name']?> </a>
                        <span class="product-description">
 						    Ref. No. : <?=$leadValue['assign_id']?> 
					 <?php  
					 if($leadValue['open_date']!="" and $leadValue['open_status']==0){
						 echo '<div class="timerCls"><a href="javascript:void(0)" data-placement="bottom" style="color:red" data-toggle="tooltip" data-original-title="'.date("d M Y h:i A",$leadValue['open_date']).'">Due since:'.$this->QueryDashboardObj->GetdateTimeFormate($leadValue['open_date']).'</a></div>';
					 }?>
						  
                        </span>
                  </div>
                </li>
              <?php }?> 
                </ul>
				<div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
		
		 
        <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-info style_7">
            <div class="box-header with-border">
              <h3 class="box-title">Bucket List (<?=$this->DelayCount?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-7">
             <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable7">
               <?php
             foreach($this->DelayData as $DelayValue)
			 {
			 ?>
                <li id="<?=$DelayValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$DelayValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$DelayValue['email_id']?>"><?=$DelayValue['name']?> </a>
                        <span class="product-description">
                           	 	Follow up Date : <?=($DelayValue['remainder_date'])?date("d M Y",$DelayValue['remainder_date']):date("d M Y",$DelayValue['assign_follow_up_date'])?>
						  <br>Ref. No. : <?=$DelayValue['assign_id']?>
                        </span>
                  </div>
                </li>
                
              <?php }?>
                </ul>
				<div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
		
		
        
        <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-primary style_2">
            <div class="box-header with-border">
              <h3 class="box-title"> Contact Made (<?=$this->ContactMadeCount?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style_2">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable2">
            <?php
             foreach($this->ContactMadeData as $ContactMadeValue)
			 {
			 ?>
                <li id="<?=$ContactMadeValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$ContactMadeValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$ContactMadeValue['email_id']?>"><?=$ContactMadeValue['name']?> </a>
                        <span class="product-description">
                           	Follow up Date : <?=date("d M Y",$ContactMadeValue['assign_follow_up_date'])?>
						  <br>Ref. No. : <?=$ContactMadeValue['assign_id']?>
                        </span>
                  </div>
                </li>
                
              <?php } ?> 
              </ul>
			  <div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
        
        
        <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-warning">
            <div class="box-header with-border">
              <h3 class="box-title"> Quoted (<?=$this->QuotedCount?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-3">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable3">
            <?php
             foreach($this->QuotedData as $QuotedValue)
			 {
			 ?>
                <li id="<?=$QuotedValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$QuotedValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$QuotedValue['email_id']?>"><?=$QuotedValue['name']?> </a>
                        <span class="product-description">
                          	Shifted On  : <?=date("d M Y",$QuotedValue['update_status_date'])?>
						  <br>Ref. No. : <?=$QuotedValue['assign_id']?>
                        </span>
                  </div>
                </li>
                
              <?php }?>
              </ul>
			  <div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
            
     
		
        <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid box-success">
            <div class="box-header with-border">
              <h3 class="box-title"> Converted (<?=$this->ConvertedCount?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-5">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable5">
                <?php
             foreach($this->ConvertedData as $ConvertedValue)
			 {
			 ?>
                <li id="<?=$ConvertedValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$ConvertedValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$ConvertedValue['email_id']?>"><?=$ConvertedValue['name']?> </a>
                        <span class="product-description">
 						   	Shifted On : <?php echo date("d M Y",$ConvertedValue['update_status_date']);?>
 						  <br>Ref. No. : <?=$ConvertedValue['assign_id']?>
                        </span>
                  </div>
                </li>
                
              <?php }?>
                </ul>
				<div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
     
		       
        <div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid  box-danger ">
            <div class="box-header with-border">
              <h3 class="box-title">Client Not Interested (<?=$this->NotInterestedCount?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style-6">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable6">
               <?php
             foreach($this->NotInterestedData as $NotInterestedValue)
			 {
			 ?>
                <li id="<?=$NotInterestedValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$NotInterestedValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$NotInterestedValue['email_id']?>"><?=$NotInterestedValue['name']?> </a>
                        <span class="product-description">
                          Shifted On : <?php echo date("d M Y",$NotInterestedValue['update_status_date']);?>
 						   <br>Ref. No. : <?=$NotInterestedValue['assign_id']?>
                        </span>
                  </div>
                </li>
                
              <?php }?>
                </ul>
				<div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
		<div class="col-md-2 width14prc">
          <!-- AREA CHART -->
           <!-- /.box -->
           <!-- DONUT CHART -->
          <div class="box box-solid style_6 ">
            <div class="box-header with-border">
              <h3 class="box-title">Lost deals (<?=$this->LostDealsCount?>)</h3>
             </div>
            <div class="box-body scrollbar" id="style_6">
            <ul class="products-list product-list-in-box connectedSortable box-height" id="sortable6">
               <?php
             foreach($this->LostDealsData as $LostValue)
			 {
			 ?>
                <li id="<?=$LostValue['assign_id']?>" class="item" onclick="OpenQueryDetailsPopUp(<?=$LostValue['assign_id']?>)">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title" data-placement="bottom" data-toggle="tooltip" data-original-title="<?=$LostValue['email_id']?>"><?=$LostValue['name']?> </a>
                        <span class="product-description">
 						   Shifted On : <?php echo date("d M Y",$LostValue['update_status_date']);?>
 						   <br>Ref. No. : <?=$LostValue['assign_id']?>
                        </span>
                  </div>
                </li>
                
              <?php }?>
                </ul>
				<div class="force-overflow"></div>
             </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

        </div>
        
		
		
</div>        
 <script src="<?=PUBLICURL?>plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
 
  <script>
   $(document).ready(function() {
    //////////////////////////////////////////////////////
	$(".select2").select2();
	$('[data-toggle="tooltip"]').tooltip();
 	//////////////////////////////////////////////////////
});
function showConversionSummary()
{
	$("#showConversionSummaryDiv").show();
	$("#ConversionBtn").html('<a href="javascript:" class="label label-info" onclick="hideConversionSummary()">Hide Conversion Summary</a>');
	getShowconversionSummaryData();
}
function hideConversionSummary()
{
	$("#showConversionSummaryDiv").hide();
	$("#ConversionBtn").html('<a href="javascript:" class="label label-info" onclick="showConversionSummary()">Show Conversion Summary</a>');
}

 

  </script>