<?php if ($this->pageCount): ?>
<div class="paginationControl">

<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" class="link1">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="link1">&lt; Previous</span> |
<?php endif; ?>


<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>" class="link1">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>


<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>" class="link1">
    Next &gt;
  </a>
<?php else: ?>
  <span class="link1">Next &gt;</span>
<?php endif; ?>

</div>
<?php endif; ?>

