 <?php $date = new Zend_Date();?>
  <title>Admin | Dashboard</title>
 
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Manage Profile</h1>
      <!-- <div class="breadcrumb">
      <input class="btn btn-primary btn-sm btn-flat" type="button" value="Delete"  onclick="javascript:delRecord();" >
      <a class="btn btn-primary btn-sm btn-flat">Add Profile</a>
      </div>-->
    </section>
      <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-8">
           <div class="box">
            <!-- /.box-header -->
            <div class="box-body">  
			  <table id="example1" class="table table-bordered table-striped table-responsive">
              <thead>
                 <tr>
 				 <th>Sr. No.</th>
				 <th>Profile Name</th>
				 <th>Website</th>
                 <th>Website Email</th>
                 <th>Created Date</th>
                 <th>Action</th> 
  				 </tr>
                 </thead>
                       <tbody>  
                          <?php $i=1;
                          foreach($this->profileData as $profile)
						  {
						  ?>
                                <tr>
                                <td><?=$i;?></td>
								<td><?php echo $profile['profile_name'];?></td>
								<td><?php echo $profile['website_name'];?></td>
                                <td><?php echo $profile['website_email'];?></td>
								<td><?php echo $profile['created_on']; ?></td>
								<td>
                                <a href="javascript:" onclick="EditProfile(<?=$profile['id']?>)"><img src="<?=PUBLICURL?>images/edit.gif"></a>
								
                              </td>
  							</tr>
                    <?php $i++; }?>
                  </tbody>
              </table>
			  
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
		<div class="col-xs-4">
		<div class="box">
            <!-- /.box-header -->
            <div class="box-body p-2">
              <h1>Add Profile</h1>
             <form method="post" id="user_form" name="user_form">
			 <input type="hidden" name="profile_id" id="profile_id">
              <div class="box-body">
                <div class="form-group">
                  <label for="profile_name">Profile Name<span class="error">*</span></label>
                  <input type="text" name="profile_name" id="profile_name" class="form-control" />
				  <div class="error" id="profile_nameError"></div>
				</div>
			 
			 
				 
				
				<div class="form-group">
                  <label for="website_id">Website Name<span class="error">*</span></label>
                  <select name="website" id="website" class="form-control">
				  <option value="">Select Website</option>
				  <?php foreach($this->websiteData as $website){?>
				  <option value="<?=$website['id']?>"><?=$website['website']?></option>
				  <?php }?>
				  </select>
				  <div class="error" id="websiteError"></div>
				</div>
			 
				<div class="form-group">
                  <label for="website_email">Website Email Id<span class="error">*</span></label>
                  <input class="form-control" name="website_email" id="website_email"> 
				  <div class="error" id="website_emailError"></div>
				</div>
				
				<div class="form-group">
                  <label for="signature">Signature<span class="error">*</span></label>
                  <textarea class="form-control textarea" name="signature" id="signature"></textarea> 
				  <div class="error" id="signatureError"></div>
				</div>
				  
				  <div class="row form-group">
				<div class="col-sm-12">
				<div class="box-footer">
                <input type="reset"  class="btn btn-danger" value="Reset" /> &nbsp;&nbsp;
                <input type="button" name="submitBtn" id="submitBtn" class="btn btn-primary" onclick="return ValidateForm()" value="Submit" />
              </div>
				</div>
				</div>
				  
                  </div>
              <!-- /.box-body -->
            </form>
          
		 </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
 
		</div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
 
  </div>
   
  <script type="text/javascript">

function checkAll(checkname, exby) {
  for (i = 0; i < checkname.length; i++)
  checkname[i].checked = exby.checked? true:false
 }
 
 
function delRecord(int_dogid)
{    
    var formobj=document.form1;
	if(check_mul(formobj))
	{
	if(confirm("Are you sure you want to delete record!"))
	{
		var formobj=document.form1;
		formobj.action="?Action=Delete";
		formobj.submit();
	} 
	}
}

 

function check_one(formObj)
{
	count=0;
	for (var i=0;i < formObj.length;i++) 
    {
		fldObj = formObj.elements[i];
		if (fldObj.type == 'checkbox')
		{
			if(fldObj.checked == true)
			{
				count=count+1;
			}
		}
    }
	if(count>1)
	{
		alert("please select only one record");
		return false;
	}
	if(count==0)
	{
		alert("Please select a record");
		return false;
	}
	return true;
}

function check_mul(formObj)
{
	count=0;
	for (var i=0;i < formObj.length;i++) 
    {
		fldObj = formObj.elements[i];
		if (fldObj.type == 'checkbox')
		{
			if(fldObj.checked == true)
			{
				count=count+1;
			}
		}
    }
	if(count==0)
	{
		alert("Please select a record");
		return false;
	}
	return true;
}

 
 
</script>

<script>
  $(document).ready(function() {
    $("#example1").DataTable();
	$('.textarea').wysihtml5();
   });
   
  function ValidateForm()
 { var error="";
	
if($("#profile_name").val()=="")
{
$("#profile_nameError").html("Please enter profile name");
error=1;	
}
if($("#website").val()=="")
{
$("#websiteError").html("Please select website");
error=1;	
}
if($("#website_email").val()=="")
{
$("#website_emailError").html("Please enter website email");
error=1;	
}
 

if(error==1)
{
	return false;
}	
else
{  
$.ajax({
    type : 'POST',
    url : '<?=SITEURL?>manageuser/profile/save-user-profile',
    data :$('#user_form').serialize(),
	cache:false,
	beforeSend: function()
	{

 	},
	success: function(response)
	{
	$.ajax('<?=SITEURL?>manageuser/profile?ajaxify=1', {
	    success: function(response) {
		$("#content").html(response);
		
		$(".content").prepend('<div class="alert alert-success alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><i class="icon fa fa-check"></i> Profile submitted successfully.</div>');
        $('html, body').animate({scrollTop: '0px'}, 0);
		
		
	    }
        });
	 
	}
  });	
}
 }
 function EditProfile(id)
 {
$.ajax({
    type : 'POST',
    url : '<?=SITEURL?>manageuser/profile/get-profile-info',
    data :"id="+id,
	cache:false,
	dataType: 'json',
	beforeSend: function()
	{

 	},
	success: function(response)
	{
	 
	$("#profile_id").val(response.id);
	$("#profile_name").val(response.profile_name);
	$("#website").val(response.website);
	$("#website_email").val(response.website_email);
	//$("#signature").val(response.signature);
	$('.wysihtml5-sandbox').contents().find('.wysihtml5-editor').html(response.signature);

 
	}
  });	 
 }


</script>