<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Change Password
       </h1>
       
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-9">
          <!-- general form elements -->
          <div class="box box-primary">
          <?=$this->errors;?>
             <!-- form start -->
            <form role="form" action="" method="post" id="user_form" name="user_form">
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Old Password<span class="error">*</span></label>
                  <input type="password" name="old_password" id="old_password" class="form-control" value="" />
				  <div class="error" id="old_passwordError"></div>
                 </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">New Password<span class="error">*</span></label>
                  <input type="password" name="new_password" id="new_password" class="form-control" value="" />
				  <div class="error" id="new_passwordError"></div>
                 </div>
                 
                 <div class="form-group">
                   
                 
                  <div class="form-group">
                  <label for="exampleInputPassword1">Confirm New Password<span class="error">*</span></label>
                   <input type="password" name="cpassword" id="cpassword" class="form-control" value="" />
				   <div class="error" id="cpasswordError"></div>
                 </div>
               
                 
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                 <input type="submit" name="submitBtn" id="submitBtn" class="btn btn-primary" value="Change Password" onclick="return ValidatePassword()" />
              </div>
            </form>
          </div>
          <!-- /.box -->

       

        </div>
        <!--/.col (left) -->
        <!-- right column -->
         
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <script type="text/javascript">
  function ValidatePassword()
  {
	  var error="";
	 if(document.user_form.old_password.value=="")
	 {
		 $("#old_passwordError").html("Please enter old password");
		 error=1;
	 }	
    if(document.user_form.new_password.value=="")
	 {
		 $("#new_passwordError").html("Please enter new password");
		 error=1;
	 }	
    if(document.user_form.cpassword.value=="")
	 {
		 $("#cpasswordError").html("Please enter confirm password");
		 error=1;
	 }	
   else if(document.user_form.cpassword.value!=document.user_form.new_password.value)
	 {
		 $("#cpasswordError").html("Please enter confirm password same as password");
		 error=1;
	 }
 
if(error==1)
{
	return false;
}	
else
{
	return true;
}
  }
  
 
</script>