 <?php $date = new Zend_Date();?>
 
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>SMS Template</h1>
       
    </section>
     <!-- Main content -->
    <section class="content">
      <div class="row">
	  
        <div class="col-xs-8">
           <div class="box">
            <!-- /.box-header -->
			
			  
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped table-responsive">
              <thead>
                 <tr>
 								<th>Sr. No.</th>
								<?php if($this->userInfo->user_type=="admin"){?>
 								<th>Category</th>
								<?php }?>
								<th>Template  Name</th>
								<th>Service</th>
								<th>Website</th>
								<th>Subject</th>
                                <th>Action</th>
  							</tr>
                       </thead>
                       <tbody>  
                          <?php $i=1;
                          foreach($this->templateData as $temp)
						  {
						  ?>
                             <tr>
                             <td><?=$i;?></td>
							 <?php if($this->userInfo->user_type=="admin"){?>
							 <td><?php echo $temp['category'];?></td>
							 <?php }?>
							 <td><?php echo $temp['template_name'];?></td>
							 <td><?php echo $temp['service_name'];?></td>
							 <td><?php echo $temp['website_name'];?></td>
							 <td><?php echo $temp['mail_subject'];?></td>
                             <td>
                                <a href="javascript:" onclick="EditTemplate(<?=$temp['id']?>)"><img src="<?=PUBLICURL?>images/edit.gif"></a>
                             </td>
  							</tr>
                         <?php $i++; }?>
                 
                 </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
      
	  </div>
       
<div class="col-xs-4">
<div class="box">
            <!-- /.box-header -->
            <div class="box-body p-2">
              <h1>Add Template</h1>
             <form method="post" id="user_form" name="user_form">
			 <input type="hidden" name="temp_id" id="temp_id">
              <div class="box-body">
			  
			   <?php if($this->userInfo->user_type=="admin"){?>
			 
                  <div class="form-group">
                  <label for="exampleInputPassword1">Category</label>
				  <div class="row">
                  <div class="col-sm-6">
				  <input type="radio" required name="category" id="category1" class="flat-red" value="PhD" >
				  <label for="category1">PhD</label>
				  </div>
				  <div class="col-sm-6">
				  <input type="radio" required name="category" id="category2" class="flat-red" value="Sales" >
				  <label for="category2">Sales</label>
				  </div>
				  </div>
				  <div id="category1Error" class="error"></div>
                   </div>
                  
				<?php } else { ?>
					<input type="text" name="category" id="category" class="flat-red" value="<?=$this->userInfo->category?>" >
				<?php }?>
			  
			  
                <div class="form-group">
                  <label for="template_name">Template Name<span class="error">*</span></label>
                  <input type="text" name="template_name" id="template_name" class="form-control" value="<?php echo $this->teamInfo['template_name'];?>" />
				  <div class="error" id="template_nameError"></div>
				</div>
				<div class="form-group">
                  <label for="service_id">Service<span class="error">*</span></label>
                  <select name="service_id" id="service_id" class="form-control">
				  <option value="">Select Service</option>
				  <?php foreach($this->serviceData as $service){?>
				  <option value="<?=$service['id']?>"><?=$service['name']?></option>
				  <?php }?>
				  </select>
				  <div class="error" id="service_idError"></div>
				</div>
				
				<div class="form-group">
                  <label for="website_id">Website Name<span class="error">*</span></label>
                  <select name="website_id" id="website_id" class="form-control">
				  <option value="">Select Website</option>
				  <?php foreach($this->websiteData as $website){?>
				  <option value="<?=$website['id']?>"><?=$website['website']?></option>
				  <?php }?>
				  </select>
				  <div class="error" id="website_idError"></div>
				</div>
			 
				<div class="form-group">
                  <label for="mail_body">SMS Body<span class="error">*</span></label>
                  <textarea class="form-control" name="sms_body" id="sms_body" placeholder="Place some text here"></textarea>
				  <div class="error" id="sms_bodyError"></div>
				</div>
				
				
				  
				  <div class="row form-group">
				<div class="col-sm-12">
				<div class="box-footer">
                <input type="reset"  class="btn btn-danger" value="Reset" onclick="ResetForm()" /> &nbsp;&nbsp;
                <input type="button" name="submitBtn" id="submitBtn" class="btn btn-primary" onclick="return ValidateForm()" value="Submit" />
              </div>
				</div>
				</div>
				  
                  </div>
              <!-- /.box-body -->
            </form>
          
		 </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
      
</div>

	   <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
 
  </div>
     
<script src="<?=PUBLICURL?>plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
  <script type="text/javascript">

function checkAll(checkname, exby) {
  for (i = 0; i < checkname.length; i++)
  checkname[i].checked = exby.checked? true:false
 }
 
 
function delRecord(int_dogid)
{    
    var formobj=document.form1;
	if(check_mul(formobj))
	{
	if(confirm("Are you sure you want to delete record!"))
	{
		var formobj=document.form1;
		formobj.action="?Action=Delete";
		formobj.submit();
	} 
	}
}

 

function check_one(formObj)
{
	count=0;
	for (var i=0;i < formObj.length;i++) 
    {
		fldObj = formObj.elements[i];
		if (fldObj.type == 'checkbox')
		{
			if(fldObj.checked == true)
			{
				count=count+1;
			}
		}
    }
	if(count>1)
	{
		alert("please select only one record");
		return false;
	}
	if(count==0)
	{
		alert("Please select a record");
		return false;
	}
	return true;
}

function check_mul(formObj)
{
	count=0;
	for (var i=0;i < formObj.length;i++) 
    {
		fldObj = formObj.elements[i];
		if (fldObj.type == 'checkbox')
		{
			if(fldObj.checked == true)
			{
				count=count+1;
			}
		}
    }
	if(count==0)
	{
		alert("Please select a record");
		return false;
	}
	return true;
}
</script>

  <script>
  $(function () {
	  $('#filter_date').daterangepicker();
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": true
    });
  });
  
 function ValidateForm()
 { var error="";
 <?php if($this->userInfo->user_type=="admin"){?>
if(document.user_form.category1.checked==false && document.user_form.category2.checked==false)
{
$("#category1Error").html("Please select category");
error=1;	
}
 <?php }?> 	
if($("#template_name").val()=="")
{
$("#template_nameError").html("Please enter template name");
error=1;	
}
if($("#service_id").val()=="")
{
$("#service_idError").html("Please select service");
error=1;	
}
if($("#website_id").val()=="")
{
$("#website_idError").html("Please select website");
error=1;	
}
 
if($("#sms_body").val()=="")
{
$("#sms_bodyError").html("Please enter mail body");
error=1;	
}

if(error==1)
{
	return false;
}	
else
{
$.ajax({
    type : 'POST',
    url : '<?=SITEURL?>template/index/savesms-template',
    data :$('#user_form').serialize(),
	cache:false,
	beforeSend: function()
	{

 	},
	success: function(response)
	{
	$.ajax('<?=SITEURL?>template/smstemplate?ajaxify=1', {
	    success: function(response) {
		$("#content").html(response);
		
		$(".content").prepend('<div class="alert alert-success alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><i class="icon fa fa-check"></i> SMS template submitted successfully.</div>');
        $('html, body').animate({scrollTop: '0px'}, 0);
		
		
	    }
        });
	
	
	
 
	}
  });	
}
 }
 
  function ResetForm()
 {
	$("#temp_id").val(''); 
 }
 
 function EditTemplate(id)
 {
$.ajax({
    type : 'POST',
    url : '<?=SITEURL?>template/index/get-template-info',
    data :"id="+id+"&table=tbl_sms_template",
	cache:false,
	dataType: 'json',
	beforeSend: function()
	{

 	},
	success: function(response)
	{
	 <?php if($this->userInfo->user_type=="admin"){?>
	  if(response.category=='PhD')
	  {
		document.getElementById("category1").checked = true;  
	  }
	  if(response.category=='Sales')
	  {
		document.getElementById("category2").checked = true;  
	  }
	  <?php } else {?>
	  $("#category").val(response.category);
	  <?php }?>
	$("#temp_id").val(response.id);
	$("#template_name").val(response.template_name);
	$("#service_id").val(response.service_id);
	$("#website_id").val(response.website_id);
	$("#sms_body").val(response.sms_body);
	 

 
	}
  });	 
 }



</script>